ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.canner("gtocore:rhenium_plasma_containment_cell")
        .notConsumable("gtceu:naquadah_nanites")
        .itemInputs("gtocore:plasma_containment_cell")
        .itemOutputs("gtocore:rhenium_plasma_containment_cell")
        .inputFluids("gtceu:degenerate_rhenium_plasma 1000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(20)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.canner("gtocore:charged_triplet_neutronium_sphere")
        .notConsumable("gtceu:neutronium_nanites")
        .itemInputs("gtocore:triplet_neutronium_sphere")
        .inputFluids("gtceu:free_alpha_gas 1000")
        .itemOutputs("gtocore:charged_triplet_neutronium_sphere")
        .EUt(500000)
        .duration(200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.canner("gtocore:awakened_draconium_plasma_containment_cell")
        .notConsumable("gtceu:draconium_nanites")
        .inputFluids("gtceu:awakened_draconium_plasma 1000")
        .itemInputs("gtocore:plasma_containment_cell")
        .itemOutputs("gtocore:awakened_draconium_plasma_containment_cell")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(20)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.canner("gtocore:dense_neutron_plasma_cell")
        .notConsumable("gtceu:neutronium_nanites")
        .inputFluids("gtceu:dense_neutron_plasma 1000")
        .itemInputs("gtocore:extremely_durable_plasma_cell")
        .itemOutputs("gtocore:dense_neutron_plasma_cell")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(20)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.canner("gtocore:chaos_containment_unit")
        .notConsumable("gtceu:cosmic_neutronium_nanites")
        .inputFluids("gtceu:chaos_plasma 1000")
        .itemInputs("gtocore:time_dilation_containment_unit")
        .itemOutputs("gtocore:chaos_containment_unit")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(20)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.canner("gtocore:infused_breath")
        .inputFluids("enderio:xp_juice 1000")
        .itemInputs("minecraft:dragon_breath")
        .itemOutputs("gtocore:infused_breath")
        .EUt(480)
        .duration(400)
        .cleanroom(GTOCleanroomType.LAW_CLEANROOM)

    gtr.canner("gtocore:cosmic_mesh_containment_unit")
        .notConsumable("gtceu:uruium_nanites")
        .itemInputs("gtocore:time_dilation_containment_unit")
        .inputFluids("gtceu:cosmic_mesh_plasma 1000")
        .itemOutputs("gtocore:cosmic_mesh_containment_unit")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(20)

    gtr.canner("gtocore:bose_einstein_cooling_container")
        .notConsumable("gtceu:iridium_nanites")
        .inputFluids("gtceu:rubidium 288")
        .itemInputs("gtocore:empty_laser_cooling_container")
        .itemOutputs("gtocore:bose_einstein_cooling_container")
        .EUt(90000)
        .duration(280)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.canner("gtocore:sculk")
        .itemInputs("minecraft:dirt", "minecraft:sculk_vein")
        .inputFluids("enderio:xp_juice 10")
        .itemOutputs("minecraft:sculk")
        .EUt(480)
        .duration(600)

    gtr.canner("gtocore:crystal_matrix_plasma_containment_cell")
        .notConsumable("gtceu:enderium_nanites")
        .inputFluids("gtceu:crystal_matrix_plasma 1000")
        .itemInputs("gtocore:plasma_containment_cell")
        .itemOutputs("gtocore:crystal_matrix_plasma_containment_cell")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(20)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.canner("gtocore:actinium_superhydride_plasma_containment_cell")
        .notConsumable("gtceu:infuscolium_nanites")
        .inputFluids("gtceu:actinium_superhydride_plasma 1000")
        .itemInputs("gtocore:plasma_containment_cell")
        .itemOutputs("gtocore:actinium_superhydride_plasma_containment_cell")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(20)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.canner("gtocore:reactor_uranium_simple")
        .itemInputs("gtocore:reactor_fuel_rod", "16x gtceu:uranium_dust")
        .inputFluids("gtceu:uranium_235 96")
        .itemOutputs("gtocore:reactor_uranium_simple")
        .EUt(1920)
        .duration(120)

    gtr.canner("gtocore:reactor_thorium_simple")
        .itemInputs("gtocore:reactor_fuel_rod", "12x gtceu:thorium_dust")
        .itemOutputs("gtocore:reactor_thorium_simple")
        .EUt(480)
        .duration(120)

    gtr.canner("gtocore:reactor_mox_simple")
        .itemInputs("gtocore:reactor_fuel_rod", "18x gtceu:uranium_dust")
        .inputFluids("gtceu:plutonium 432")
        .itemOutputs("gtocore:reactor_mox_simple")
        .EUt(7680)
        .duration(120)

    gtr.canner("gtocore:reactor_naquadah_simple")
        .itemInputs("gtocore:tungsten_carbide_reactor_fuel_rod", "4x gtceu:naquadah_dust")
        .inputFluids("gtceu:thorium 144")
        .itemOutputs("gtocore:reactor_naquadah_simple")
        .EUt(30720)
        .duration(120)
})