ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.chemical_reactor("gtocore:caesium_iodide_dust")
        .itemInputs("gtceu:caesium_dust", "gtceu:iodine_dust")
        .itemOutputs("2x gtceu:caesium_iodide_dust")
        .EUt(30)
        .duration(100)

    gtr.chemical_reactor("gtocore:acetylene")
        .itemInputs("3x gtceu:calcium_carbide_dust")
        .inputFluids("minecraft:water 2000")
        .outputFluids("gtceu:acetylene 1000")
        .itemOutputs("5x gtceu:calcium_hydroxide_dust")
        .EUt(7)
        .duration(60)

    gtr.large_chemical_reactor("gtocore:co_ac_ab_catalyst_dust")
        .itemInputs("2x gtceu:charcoal_dust", "enderio:powdered_cobalt", "gtceu:polybenzimidazole_plate")
        .inputFluids("gtceu:steam 1000", "gtceu:acetylene 1000")
        .outputFluids("gtceu:hydrogen 4000", "gtceu:carbon_monoxide 1000")
        .itemOutputs("gtceu:co_ac_ab_catalyst_dust")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(20)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:sodium_nitrite_dust")
        .notConsumable("gtceu:co_ac_ab_catalyst_dust")
        .inputFluids("gtceu:sodium_nitrate_solution 1000")
        .outputFluids("gtceu:oxygen 1000", "minecraft:water 1000")
        .itemOutputs("4x gtceu:sodium_nitrite_dust")
        .EUt(30)
        .duration(300)

    gtr.chemical_reactor("gtocore:boric_acide")
        .itemInputs("23x gtceu:borax_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .outputFluids("gtceu:boric_acide 4000", "minecraft:water 5000")
        .itemOutputs("4x gtceu:salt_dust")
        .EUt(120)
        .duration(150)

    gtr.chemical_reactor("gtocore:fluoroboric_acide")
        .inputFluids("gtceu:boric_acide 1000", "gtceu:hydrofluoric_acid 4000")
        .outputFluids("gtceu:fluoroboric_acide 1000", "minecraft:water 13000")
        .EUt(120)
        .duration(150)

    gtr.chemical_reactor("gtocore:benzenediazonium_tetrafluoroborate")
        .itemInputs("4x gtceu:sodium_nitrite_dust")
        .inputFluids("gtceu:hydrochloric_acid 1000", "gtceu:fluoroboric_acide 2000")
        .outputFluids("gtceu:benzenediazonium_tetrafluoroborate 1000", "minecraft:water 2000")
        .itemOutputs("2x gtceu:salt_dust")
        .EUt(30720)
        .duration(130)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:fluorotoluene")
        .notConsumable("gtceu:blacklight")
        .inputFluids("gtceu:fluoroantimonic_acid 1000", "gtceu:methane 1000", "gtceu:fluoro_benzene 1000")
        .outputFluids("gtceu:fluorotoluene 1000", "minecraft:water 4000")
        .itemOutputs("4x gtceu:antimony_trifluoride_dust")
        .EUt(480)
        .duration(150)

    gtr.chemical_reactor("gtocore:hydroquinone")
        .inputFluids("gtceu:benzene 2000", "gtceu:oxygen 5000", "gtceu:propene 1000")
        .outputFluids("gtceu:hydroquinone 1000", "gtceu:resorcinol 1000", "gtceu:acetone 1000")
        .EUt(1920)
        .duration(200)
        .circuit(2)

    gtr.large_chemical_reactor("gtocore:difluorobenzophenone_dust")
        .notConsumable("gtceu:znfealcl_catalyst_dust")
        .inputFluids("gtceu:fluorotoluene 1000", "gtceu:chlorine 6000", "minecraft:water 1000", "gtceu:fluoro_benzene 1000")
        .outputFluids("gtceu:hydrochloric_acid 6000")
        .itemOutputs("24x gtceu:difluorobenzophenone_dust")
        .EUt(1920)
        .duration(100)

    gtr.large_chemical_reactor("gtocore:polyetheretherketone")
        .itemInputs("24x gtceu:difluorobenzophenone_dust", "6x gtceu:soda_ash_dust")
        .inputFluids("gtceu:hydroquinone 1000")
        .outputFluids("gtceu:polyetheretherketone 2592", "minecraft:water 1000", "gtceu:carbon_dioxide 1000")
        .itemOutputs("4x gtceu:sodium_fluoride_dust")
        .EUt(122880)
        .duration(250)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:iodine_containing_slurry")
        .inputFluids("gtceu:chlorine 1000", "gtceu:enriched_potassium_iodide_slurry 1000")
        .outputFluids("gtceu:iodine_containing_slurry 1000")
        .EUt(120)
        .duration(100)

    gtr.chemical_reactor("gtocore:germanium_tetrachloride_solution")
        .itemInputs("2x gtceu:germanium_ash_dust")
        .inputFluids("gtceu:hydrochloric_acid 4000")
        .outputFluids("gtceu:germanium_tetrachloride_solution 1000")
        .EUt(120)
        .duration(200)

    gtr.chemical_reactor("gtocore:rhenium_dust")
        .inputFluids("gtceu:ammonium_perrhenate 1000", "gtceu:hydrogen 7000")
        .itemOutputs("gtceu:rhenium_dust")
        .outputFluids("gtceu:ammonia 1000", "minecraft:water 4000")
        .EUt(1920)
        .duration(80)

    gtr.chemical_reactor("gtocore:ammonium_perrhenate")
        .inputFluids("gtceu:rhenium_sulfuric_solution 1000", "gtceu:ammonia 1000")
        .outputFluids("gtceu:ammonium_perrhenate 1000", "gtceu:hydrogen_sulfide 1000")
        .EUt(480)
        .duration(150)

    gtr.chemical_reactor("gtocore:molybdenum_concentrate_dust")
        .itemInputs("3x gtceu:gold_depleted_molybdenite_dust")
        .inputFluids("gtceu:iron_iii_chloride 250")
        .itemOutputs("4x gtceu:molybdenum_concentrate_dust")
        .EUt(1920)
        .duration(10)

    gtr.chemical_reactor("gtocore:gold_depleted_molybdenite_dust")
        .itemInputs("3x gtceu:molybdenite_dust")
        .inputFluids("gtceu:sodium_cyanide 1000")
        .itemOutputs("3x gtceu:gold_depleted_molybdenite_dust")
        .outputFluids("gtceu:gold_cyanide 1000")
        .EUt(7680)
        .duration(100)

    gtr.chemical_reactor("gtocore:sodium_cyanide")
        .itemInputs("2x gtceu:sodium_dust")
        .inputFluids("gtceu:hydrogen_cyanide 2000", "gtceu:oxygen 1000")
        .outputFluids("gtceu:sodium_cyanide 2000", "minecraft:water 1000")
        .EUt(1920)
        .duration(12)

    gtr.chemical_reactor("gtocore:gold_cyanide")
        .itemInputs("gtceu:sodium_dust")
        .inputFluids("gtceu:gold_cyanide 1000")
        .itemOutputs("enderio:powdered_gold")
        .outputFluids("gtceu:sodium_cyanide 1000")
        .EUt(1920)
        .duration(140)

    gtr.chemical_reactor("gtocore:carbon_nanotubes_ingot")
        .notConsumable("gtceu:rhenium_plate")
        .inputFluids("gtceu:methane 800", "gtceu:cycloparaphenylene 200")
        .itemOutputs("gtceu:carbon_nanotubes_ingot")
        .circuit(1)
        .EUt(320000)
        .duration(290)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:cycloparaphenylene")
        .itemInputs("23x gtceu:dichlorocyclooctadieneplatinium_dust", "8x gtceu:carbon_dust", "4x gtceu:diiodobiphenyl_dust")
        .inputFluids("gtceu:trimethyltin_chloride 4000", "gtceu:silver_tetrafluoroborate 4000")
        .itemOutputs("3x gtceu:platinum_raw_dust", "4x gtceu:silver_dust")
        .outputFluids("gtceu:cycloparaphenylene 10000", "gtceu:boron_fluoride 4000", "gtceu:1_octene 3000", "gtceu:hydrofluoric_acid 4000")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(800)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:dichlorocyclooctadieneplatinium_dust")
        .itemInputs("gtceu:platinum_dust", "2x gtceu:potassium_dust")
        .inputFluids("gtceu:nitric_acid 4000", "gtceu:hydrochloric_acid 4000", "gtceu:cyclooctadiene 1000")
        .itemOutputs("23x gtceu:dichlorocyclooctadieneplatinium_dust", "4x gtceu:rock_salt_dust")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(400)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:cyclooctadiene")
        .notConsumable("gtceu:nickel_dust")
        .inputFluids("gtceu:butadiene 2000")
        .outputFluids("gtceu:cyclooctadiene 1000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(200)

    gtr.large_chemical_reactor("gtocore:diiodobiphenyl_dust")
        .notConsumable("gtceu:blacklight")
        .itemInputs("2x gtceu:iodine_dust", "22x gtceu:biphenyl_dust")
        .outputFluids("gtceu:hydrogen 2000")
        .itemOutputs("22x gtceu:diiodobiphenyl_dust")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(200)

    gtr.chemical_reactor("gtocore:formaldehyde")
        .notConsumable("gtceu:silver_dust")
        .inputFluids("gtceu:methanol 1000", "gtceu:oxygen 1000")
        .outputFluids("gtceu:formaldehyde 1000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(200)

    gtr.chemical_reactor("gtocore:acetaldehyde")
        .notConsumable("gtceu:osmium_tetroxide_dust")
        .inputFluids("gtceu:acetone 1000", "gtceu:oxygen 1000")
        .outputFluids("gtceu:formaldehyde 1000", "gtceu:acetaldehyde 1000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(320)

    gtr.large_chemical_reactor("gtocore:trimethyltin_chloride")
        .notConsumable("gtceu:magnesium_dust")
        .itemInputs("enderio:powdered_tin")
        .inputFluids("gtceu:methane 3000", "gtceu:oxygen 1000", "gtceu:chlorine 2000")
        .outputFluids("gtceu:trimethyltin_chloride 1000", "gtceu:diluted_hydrochloric_acid 2000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(320)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:silver_tetrafluoroborate")
        .itemInputs("6x gtceu:silver_dust")
        .inputFluids("gtceu:boron_fluoride 2000", "gtceu:oxygen 3000")
        .outputFluids("gtceu:silver_tetrafluoroborate 6000")
        .itemOutputs("5x gtceu:boron_trioxide_dust")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(200)

    gtr.chemical_reactor("gtocore:boron_fluoride")
        .itemInputs("5x gtceu:boron_trioxide_dust")
        .inputFluids("gtceu:hydrofluoric_acid 6000")
        .outputFluids("gtceu:boron_fluoride 2000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(200)

    gtr.chemical_reactor("gtocore:pyridine")
        .inputFluids("gtceu:formaldehyde 2000", "gtceu:acetaldehyde 1000", "gtceu:ammonia 1000")
        .outputFluids("gtceu:pyridine 1000", "gtceu:hydrogen 2000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(240)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:potassium_bisulfite_dust")
        .itemInputs("6x gtceu:potassium_carbonate_dust")
        .inputFluids("gtceu:sulfur_dioxide 2000", "minecraft:water 1000")
        .itemOutputs("12x gtceu:potassium_bisulfite_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(160)

    gtr.chemical_reactor("gtocore:potassium_hydroxylaminedisulfonate_dust")
        .itemInputs("12x gtceu:potassium_bisulfite_dust")
        .inputFluids("gtceu:nitrous_acid 1000")
        .itemOutputs("13x gtceu:potassium_hydroxylaminedisulfonate_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(200)

    gtr.chemical_reactor("gtocore:hydroxylammonium_sulfate_dust")
        .itemInputs("26x gtceu:potassium_hydroxylaminedisulfonate_dust")
        .inputFluids("minecraft:water 4000")
        .itemOutputs("17x gtceu:hydroxylammonium_sulfate_dust", "14x gtceu:potassium_sulfate_dust")
        .outputFluids("gtceu:sulfuric_acid 1000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(200)

    gtr.chemical_reactor("gtocore:hexanitrohexaaxaisowurtzitane_dust")
        .inputFluids("gtceu:ethylenediamine 1000")
        .itemInputs("36x gtceu:crude_hexanitrohexaaxaisowurtzitane_dust", "3x gtceu:silica_gel_dust")
        .itemOutputs("36x gtceu:hexanitrohexaaxaisowurtzitane_dust")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(100)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:ethylenediamine")
        .notConsumable("gtceu:palladium_dust")
        .inputFluids("gtceu:ammonia 1000", "gtceu:ethanolamine 1000")
        .outputFluids("gtceu:ethylenediamine 1000", "minecraft:water 1000")
        .EUt(120)
        .duration(180)

    gtr.chemical_reactor("gtocore:ethanolamine")
        .inputFluids("gtceu:ammonia 1000", "gtceu:ethylene_oxide 1000")
        .outputFluids("gtceu:ethanolamine 1000")
        .EUt(7680)
        .duration(60)

    gtr.chemical_reactor("gtocore:ethylene_oxide")
        .inputFluids("gtceu:oxygen 1000", "gtceu:ethylene 1000")
        .outputFluids("gtceu:ethylene_oxide 1000")
        .EUt(480)
        .circuit(4)
        .duration(80)

    gtr.chemical_reactor("gtocore:crude_hexanitrohexaaxaisowurtzitane_dust")
        .inputFluids("minecraft:water 4000")
        .itemInputs("46x gtceu:tetraacetyldinitrosohexaazaisowurtzitane_dust", "48x gtceu:nitronium_tetrafluoroborate_dust")
        .itemOutputs("36x gtceu:crude_hexanitrohexaaxaisowurtzitane_dust", "14x gtceu:nitrosonium_tetrafluoroborate_dust")
        .outputFluids("gtceu:fluoroboric_acide 4000", "gtceu:acetic_acid 4000")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:nitronium_tetrafluoroborate_dust")
        .inputFluids("gtceu:boron_fluoride 1000", "gtceu:hydrofluoric_acid 1000", "gtceu:nitric_acid 1000")
        .itemOutputs("8x gtceu:nitronium_tetrafluoroborate_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(1920)
        .duration(40)

    gtr.chemical_reactor("gtocore:tetraacetyldinitrosohexaazaisowurtzitane_dust")
        .inputFluids("minecraft:water 14000")
        .itemInputs("70x gtceu:dibenzyltetraacetylhexaazaisowurtzitane_dust", "42x gtceu:nitrosonium_tetrafluoroborate_dust")
        .itemOutputs("46x gtceu:tetraacetyldinitrosohexaazaisowurtzitane_dust")
        .outputFluids("gtceu:hydrofluoric_acid 24000", "gtceu:boric_acide 6000", "gtceu:nitric_oxide 4000", "gtceu:benzaldehyde 2000")
        .EUt(7680)
        .duration(140)

    gtr.chemical_reactor("gtocore:nitrosonium_tetrafluoroborate_dust")
        .inputFluids("gtceu:boron_fluoride 2000", "gtceu:hydrofluoric_acid 2000", "gtceu:dinitrogen_tetroxide 2000")
        .itemOutputs("7x gtceu:nitrosonium_tetrafluoroborate_dust")
        .outputFluids("gtceu:nitric_acid 1000")
        .EUt(120)
        .duration(120)

    gtr.large_chemical_reactor("gtocore:dibenzyltetraacetylhexaazaisowurtzitane_dust")
        .notConsumableFluid("gtceu:hydrobromic_acid 10000")
        .itemInputs("72x gtceu:succinimidyl_acetate_dust", "102x gtceu:hexabenzylhexaazaisowurtzitane_dust")
        .inputFluids("gtceu:hydrogen 8000")
        .itemOutputs("70x gtceu:dibenzyltetraacetylhexaazaisowurtzitane_dust")
        .outputFluids("gtceu:toluene 6000")
        .EUt(122880)
        .duration(120)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:hydrobromic_acid")
        .inputFluids("gtceu:bromine 1000", "gtceu:hydrogen 1000")
        .outputFluids("gtceu:hydrobromic_acid 1000")
        .EUt(480)
        .duration(300)

    gtr.chemical_reactor("gtocore:succinimidyl_acetate_dust")
        .inputFluids("gtceu:acetic_anhydride 1000")
        .itemInputs("13x gtceu:n_hydroxysuccinimide_dust")
        .itemOutputs("18x gtceu:succinimidyl_acetate_dust")
        .outputFluids("gtceu:acetic_acid 1000")
        .EUt(7680)
        .duration(80)

    gtr.chemical_reactor("gtocore:n_hydroxysuccinimide_dust")
        .inputFluids("gtceu:methanol 40000", "gtceu:toluene 6000", "gtceu:hydroxylamine_hydrochloride 6000")
        .itemInputs("6x gtceu:sodium_dust", "66x gtceu:succinic_anhydride_dust")
        .outputFluids("minecraft:water 6000", "gtceu:hydrogen 6000")
        .itemOutputs("13x gtceu:n_hydroxysuccinimide_dust", "12x gtceu:salt_dust")
        .EUt(1920)
        .duration(220)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:succinic_anhydride_dust")
        .inputFluids("gtceu:acetic_anhydride 1000")
        .itemInputs("14x gtceu:succinic_acid_dust")
        .itemOutputs("11x gtceu:succinic_anhydride_dust")
        .outputFluids("gtceu:acetic_acid 2000")
        .EUt(7680)
        .duration(20)

    gtr.chemical_reactor("gtocore:succinic_acid_dust")
        .notConsumable("gtceu:rhodium_plated_palladium_dust")
        .inputFluids("minecraft:water 1000", "gtceu:hydrogen 1000", "gtceu:maleic_anhydride 2000")
        .itemOutputs("14x gtceu:succinic_acid_dust")
        .EUt(1920)
        .duration(200)

    gtr.chemical_reactor("gtocore:maleic_anhydride")
        .notConsumable("gtceu:bismuth_dust")
        .inputFluids("gtceu:oxygen 7000", "gtceu:butane 1000")
        .outputFluids("minecraft:water 4000", "gtceu:maleic_anhydride 1000")
        .EUt(480)
        .duration(280)

    gtr.large_chemical_reactor("gtocore:hydroxylamine_hydrochloride")
        .itemInputs("17x gtceu:hydroxylammonium_sulfate_dust", "3x gtceu:barium_chloride_dust")
        .outputFluids("gtceu:hydroxylamine_hydrochloride 2000", "minecraft:water 1000")
        .itemOutputs("6x gtceu:barite_dust")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(100)

    gtr.chemical_reactor("gtocore:nitrous_acid")
        .itemInputs("4x gtceu:sodium_nitrite_dust")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("7x gtceu:sodium_bisulfate_dust")
        .outputFluids("gtceu:nitrous_acid 1000")
        .EUt(30)
        .duration(80)

    gtr.chemical_reactor("gtocore:barium_chloride_dust")
        .inputFluids("gtceu:hydrochloric_acid 2000")
        .itemInputs("6x gtceu:barium_dust")
        .outputFluids("gtceu:hydrogen 2000")
        .itemOutputs("3x gtceu:barium_chloride_dust")
        .EUt(120)
        .duration(60)

    gtr.chemical_reactor("gtocore:hexabenzylhexaazaisowurtzitane_dust")
        .inputFluids("gtceu:benzylamine 6000", "gtceu:glyoxal 3000")
        .itemInputs("6x gtceu:acetonitrile_dust")
        .itemOutputs("102x gtceu:hexabenzylhexaazaisowurtzitane_dust")
        .EUt(7680)
        .duration(100)

    gtr.large_chemical_reactor("gtocore:acetonitrile_dust")
        .inputFluids("gtceu:ammonia 1000", "gtceu:carbon_monoxide 2000", "gtceu:hydrogen 4000")
        .outputFluids("minecraft:water 2000")
        .itemOutputs("6x gtceu:acetonitrile_dust")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:glyoxal")
        .inputFluids("gtceu:acetaldehyde 2000", "gtceu:nitric_acid 2000")
        .outputFluids("minecraft:water 3000", "gtceu:glyoxal 2000", "gtceu:nitrogen_dioxide 1000")
        .EUt(60)
        .duration(120)

    gtr.large_chemical_reactor("gtocore:benzylamine")
        .itemInputs("22x gtceu:hexamethylenetetramine_dust")
        .inputFluids("minecraft:water 6000", "gtceu:hydrochloric_acid 2000", "gtceu:benzyl_chloride 1000")
        .outputFluids("gtceu:benzylamine 1000", "gtceu:formaldehyde 6000")
        .itemOutputs("18x gtceu:ammonium_chloride_dust")
        .EUt(7680)
        .duration(200)

    gtr.chemical_reactor("gtocore:benzyl_chloride")
        .notConsumable("gtceu:blacklight")
        .inputFluids("gtceu:toluene 1000", "gtceu:chlorine 2000")
        .outputFluids("gtceu:benzyl_chloride 1000", "gtceu:hydrochloric_acid 1000")
        .EUt(480)
        .duration(200)

    gtr.chemical_reactor("gtocore:hexamethylenetetramine_dust")
        .circuit(1)
        .inputFluids("gtceu:formaldehyde 4000", "gtceu:ammonia 6000")
        .itemOutputs("22x gtceu:hexamethylenetetramine_dust")
        .outputFluids("minecraft:water 6000")
        .EUt(30)
        .duration(160)

    gtr.chemical_reactor("gtocore:rare_earth_chlorides")
        .inputFluids("gtceu:rare_earth_hydroxides 1000", "gtceu:hydrochloric_acid 1000")
        .outputFluids("gtceu:rare_earth_chlorides 1000")
        .itemOutputs("3x gtceu:sodium_hydroxide_dust")
        .EUt(30)
        .duration(120)

    gtr.large_chemical_reactor("gtocore:adamantine_dust")
        .itemInputs("2x gtceu:adamantine_compounds_dust", "17x gtceu:mirabilite_dust")
        .inputFluids("gtceu:nitration_mixture 1000", "gtceu:aqua_regia 2000", "gtceu:mana 100")
        .itemOutputs("gtceu:adamantine_dust", "5x gtceu:sodium_nitrate_dust", "7x gtceu:sodium_bisulfate_dust")
        .outputFluids("gtceu:rare_earth_chlorides 1000")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(400)

    gtr.large_chemical_reactor("gtocore:vibranium_unstable")
        .inputFluids("gtceu:bedrock_gas 1000", "gtceu:hydrochloric_acid 4000")
        .itemInputs("2x gtceu:adamantine_dust")
        .outputFluids("gtceu:vibranium_unstable 500", "gtceu:rare_earth_chlorides 1000")
        .itemOutputs("4x gtceu:iridium_chloride_dust")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(200)

    gtr.chemical_reactor("gtocore:pre_zylon_dust")
        .itemInputs("16x gtceu:terephthalaldehyde_dust")
        .inputFluids("gtceu:dinitrodipropanyloxybenzene 1000")
        .itemOutputs("gtceu:pre_zylon_dust")
        .outputFluids("gtceu:oxygen 6000")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(50)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:terephthalaldehyde_dust")
        .inputFluids("gtceu:sulfuric_acid 1000", "gtceu:dibromomethylbenzene 1000")
        .itemOutputs("16x gtceu:terephthalaldehyde_dust")
        .outputFluids("gtceu:bromine 2000", "gtceu:hydrogen_sulfide 1000", "minecraft:water 1000", "gtceu:oxygen 1000")
        .EUt(7680)
        .duration(50)

    gtr.large_chemical_reactor("gtocore:dinitrodipropanyloxybenzene")
        .itemInputs("3x gtceu:sodium_oxide_dust")
        .inputFluids("gtceu:acetic_anhydride 1000", "gtceu:isochloropropane 1000", "gtceu:resorcinol 1000", "gtceu:propene 1000", "gtceu:nitric_acid 2000")
        .outputFluids("gtceu:dinitrodipropanyloxybenzene 1000", "minecraft:water 2000", "gtceu:acetic_acid 2000")
        .EUt(7680)
        .duration(50)

    gtr.chemical_reactor("gtocore:sodium_oxide_dust")
        .itemInputs("2x gtceu:sodium_dust")
        .inputFluids("gtceu:oxygen 1000")
        .circuit(1)
        .itemOutputs("3x gtceu:sodium_oxide_dust")
        .EUt(7)
        .duration(60)

    gtr.chemical_reactor("gtocore:dibromomethylbenzene")
        .inputFluids("gtceu:bromine 2000", "gtceu:toluene 1000")
        .outputFluids("gtceu:dibromomethylbenzene 1000", "gtceu:hydrogen 2000")
        .EUt(30)
        .duration(600)

    gtr.large_chemical_reactor("gtocore:methylbenzophenanthrene_dust")
        .notConsumable("gtceu:iodine_dust")
        .inputFluids("gtceu:naphthalene 1000", "gtceu:formaldehyde 1000", "gtceu:oxygen 1000", "gtceu:ethylbenzene 1000")
        .itemOutputs("33x gtceu:methylbenzophenanthrene_dust")
        .EUt(1920)
        .duration(600)

    gtr.large_chemical_reactor("gtocore:unfolded_fullerene_dust")
        .notConsumable("gtceu:titanium_dust")
        .notConsumable("gtceu:aluminium_dust")
        .notConsumableFluid("gtceu:chlorine 1000")
        .itemInputs("102x gtceu:benzophenanthrenylacetonitrile_dust")
        .itemOutputs("gtceu:unfolded_fullerene_dust")
        .EUt(7680)
        .duration(250)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:benzophenanthrenylacetonitrile_dust")
        .itemInputs("33x gtceu:methylbenzophenanthrene_dust", "12x gtceu:bromo_succinimide_dust", "3x gtceu:potassium_cyanide_dust")
        .itemOutputs("34x gtceu:benzophenanthrenylacetonitrile_dust", "12x gtceu:succinimide_dust", "2x gtceu:potassium_bromide_dust")
        .EUt(1920)
        .duration(100)

    gtr.chemical_reactor("gtocore:bromo_succinimide_dust")
        .itemInputs("12x gtceu:succinimide_dust")
        .inputFluids("gtceu:bromine 2000")
        .outputFluids("gtceu:hydrobromic_acid 1000")
        .itemOutputs("12x gtceu:bromo_succinimide_dust")
        .EUt(120)
        .duration(100)

    gtr.chemical_reactor("gtocore:succinimide_dust")
        .inputFluids("gtceu:ammonia 1000")
        .itemInputs("14x gtceu:succinic_acid_dust")
        .outputFluids("minecraft:water 1000")
        .itemOutputs("12x gtceu:succinimide_dust")
        .EUt(120)
        .duration(100)

    gtr.large_chemical_reactor("gtocore:phenylpentanoic_acid")
        .notConsumableFluid("gtceu:trimethyltin_chloride 1000")
        .inputFluids("minecraft:water 2000", "gtceu:hydroiodic_acid 1000", "gtceu:acrylonitrile 1000", "gtceu:styrene 1000")
        .outputFluids("gtceu:phenylpentanoic_acid 1000", "gtceu:ammonia 1000")
        .itemOutputs("4x gtceu:aluminium_hydride_dust", "2x gtceu:lithium_iodide_dust")
        .EUt(8000000)
        .duration(200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:hydroiodic_acid")
        .inputFluids("gtceu:monomethylhydrazine 1000")
        .itemInputs("4x gtceu:iodine_dust")
        .outputFluids("gtceu:nitrogen 2000", "gtceu:hydroiodic_acid 4000")
        .EUt(500)
        .duration(210)

    gtr.chemical_reactor("gtocore:acrylonitrile")
        .notConsumable("gtceu:platinum_dust")
        .inputFluids("gtceu:oxygen 3000", "gtceu:ammonia 1000", "gtceu:propene 1000")
        .outputFluids("gtceu:acrylonitrile 2000", "minecraft:water 3000")
        .EUt(120)
        .duration(100)

    gtr.chemical_reactor("gtocore:titanium_tetrachloride_1")
        .inputFluids("gtceu:hydrochloric_acid 4000")
        .itemInputs("gtceu:titanium_dust")
        .outputFluids("gtceu:hydrogen 4000", "gtceu:titanium_tetrachloride 1000")
        .EUt(480)
        .duration(400)

    gtr.chemical_reactor("gtocore:titanium_tetrafluoride")
        .inputFluids("gtceu:titanium_tetrachloride 1000", "gtceu:fluorine 4000")
        .outputFluids("gtceu:chlorine 4000", "gtceu:titanium_tetrafluoride 1000")
        .EUt(1920)
        .duration(800)

    gtr.chemical_reactor("gtocore:titanium_50_tetrachloride")
        .inputFluids("gtceu:titanium_50_tetrafluoride 1000", "gtceu:hydrochloric_acid 4000")
        .outputFluids("gtceu:hydrofluoric_acid 4000", "gtceu:titanium_50_tetrachloride 1000")
        .EUt(480)
        .duration(400)

    gtr.large_chemical_reactor("gtocore:polyurethaneresin")
        .itemInputs("gtceu:pentaerythritol_dust", "5x gtceu:diphenylmethane_diisocyanate_dust")
        .inputFluids("gtceu:ethyleneglycol 4000", "gtceu:siliconoil 1000")
        .outputFluids("gtceu:polyurethaneresin 1000")
        .EUt(7680)
        .duration(600)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:diphenylmethanediisocyanatemixture")
        .inputFluids("gtceu:diaminodiphenylmethanmixture 1000", "gtceu:phosgene 2000")
        .outputFluids("gtceu:diphenylmethanediisocyanatemixture 1000")
        .EUt(7680)
        .duration(600)

    gtr.chemical_reactor("gtocore:phosgene")
        .inputFluids("gtceu:carbon_monoxide 1000", "gtceu:chlorine 2000")
        .outputFluids("gtceu:phosgene 1000")
        .EUt(1920)
        .duration(400)

    gtr.large_chemical_reactor("gtocore:diaminodiphenylmethanmixture")
        .inputFluids("gtceu:formaldehyde 1000", "gtceu:aniline 2000", "gtceu:hydrochloric_acid 1000")
        .outputFluids("gtceu:diaminodiphenylmethanmixture 1000")
        .EUt(122880)
        .duration(200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:siliconoil")
        .inputFluids("gtceu:ethylene_oxide 1000", "gtceu:dimethyldichlorosilane 4000", "gtceu:distilled_water 5000")
        .outputFluids("gtceu:siliconoil 5000")
        .EUt(480)
        .duration(1000)

    gtr.chemical_reactor("gtocore:ethyleneglycol")
        .circuit(1)
        .inputFluids("gtceu:ethylene_oxide 1000", "minecraft:water 1000")
        .outputFluids("gtceu:ethyleneglycol 1000")
        .EUt(480)
        .duration(300)

    gtr.large_chemical_reactor("gtocore:pentaerythritol_dust")
        .notConsumable("gtceu:sodium_hydroxide_dust")
        .inputFluids("gtceu:formaldehyde 4000", "gtceu:acetaldehyde 1000")
        .itemOutputs("21x gtceu:pentaerythritol_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .EUt(1920)
        .duration(1200)

    gtr.large_chemical_reactor("gtocore:sarcosine_dust")
        .inputFluids("gtceu:acetic_acid 1000", "gtceu:chlorine 2000", "gtceu:methanol 1000", "gtceu:ammonia 1000")
        .outputFluids("gtceu:diluted_hydrochloric_acid 3000")
        .itemOutputs("13x gtceu:sarcosine_dust")
        .EUt(7680)
        .duration(200)

    gtr.chemical_reactor("gtocore:ferrocene")
        .itemInputs("gtceu:zeolite_sieving_pellets_dust")
        .inputFluids("gtceu:iron_ii_chloride 1000", "gtceu:cyclopentadiene 2000")
        .outputFluids("gtceu:diluted_hydrochloric_acid 2000", "gtceu:ferrocene 1000")
        .itemOutputs("gtceu:wet_zeolite_sieving_pellets_dust")
        .EUt(30720)
        .duration(200)

    gtr.large_chemical_reactor("gtocore:palladium_fullerene_matrix_dust")
        .itemInputs("13x gtceu:sarcosine_dust", "gtceu:fullerene_dust", "gtceu:palladium_dust")
        .inputFluids("gtceu:ferrocene 1000")
        .itemOutputs("gtceu:palladium_fullerene_matrix_dust")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(100)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:pcbs")
        .itemInputs("8x gtceu:fullerene_dust")
        .notConsumable("gtceu:dmap_dust")
        .inputFluids("gtceu:phenylpentanoic_acid 8000", "gtceu:dichloromethane 8000", "gtceu:styrene 7000", "gtceu:chlorobenzene 8000", "gtceu:dimethyl_sulfide 8000")
        .outputFluids("gtceu:toluene 8000", "gtceu:hydrogen_sulfide 8000", "gtceu:hydrochloric_acid 24000", "gtceu:pcbs 8000")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(80)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:dmap_dust")
        .inputFluids("gtceu:pyridine 1000", "gtceu:dimethylamine 1000")
        .itemOutputs("gtceu:dmap_dust")
        .outputFluids("gtceu:hydrogen 2000")
        .EUt(7680)
        .duration(200)

    gtr.chemical_reactor("gtocore:dichloromethane")
        .inputFluids("gtceu:chloromethane 1000", "gtceu:chlorine 2000")
        .outputFluids("gtceu:dichloromethane 1000", "gtceu:hydrochloric_acid 1000")
        .EUt(30)
        .duration(80)

    gtr.chemical_reactor("gtocore:dimethyl_sulfide")
        .inputFluids("gtceu:methanol 2000", "gtceu:hydrogen_sulfide 1000")
        .outputFluids("gtceu:dimethyl_sulfide 1000", "minecraft:water 2000")
        .EUt(1920)
        .duration(100)

    gtr.large_chemical_reactor("gtocore:neutronium_doped_nanotubes")
        .itemInputs("gtceu:neutronium_dust")
        .notConsumable("gtceu:rhenium_plate")
        .inputFluids("gtceu:methane 800", "gtceu:cycloparaphenylene 200")
        .outputFluids("gtceu:neutronium_doped_nanotubes 1000")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(500)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:ammonium_nitrate_solution")
        .inputFluids("gtceu:ammonia 1000", "gtceu:nitric_acid 1000")
        .outputFluids("gtceu:ammonium_nitrate_solution 1000")
        .EUt(120)
        .duration(60)

    gtr.chemical_reactor("gtocore:aniline")
        .notConsumable("gtceu:zinc_dust")
        .inputFluids("gtceu:nitrobenzene 1000", "gtceu:hydrogen 3000")
        .outputFluids("gtceu:aniline 1000", "minecraft:water 2000")
        .EUt(1920)
        .duration(160)

    gtr.chemical_reactor("gtocore:durene_dust")
        .inputFluids("gtceu:chloromethane 2000", "gtceu:dimethylbenzene 1000")
        .outputFluids("gtceu:hydrochloric_acid 2000")
        .itemOutputs("24x gtceu:durene_dust")
        .EUt(120)
        .duration(150)

    gtr.chemical_reactor("gtocore:pyromellitic_dianhydride_dust")
        .itemInputs("24x gtceu:durene_dust")
        .inputFluids("gtceu:oxygen 12000")
        .outputFluids("minecraft:water 6000")
        .itemOutputs("18x gtceu:pyromellitic_dianhydride_dust")
        .EUt(120)
        .duration(150)

    gtr.chemical_reactor("gtocore:oxydianiline")
        .inputFluids("gtceu:aniline 2000", "gtceu:phenol 1000")
        .notConsumable("enderio:powdered_tin")
        .outputFluids("gtceu:oxydianiline 1000", "gtceu:methane 2000")
        .EUt(120)
        .duration(150)

    gtr.large_chemical_reactor("gtocore:paa")
        .itemInputs("18x gtceu:pyromellitic_dianhydride_dust")
        .inputFluids("gtceu:oxydianiline 1000")
        .outputFluids("gtceu:paa 1000")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(400)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:highly_reflective_mirror")
        .itemInputs("gtceu:germanium_plate")
        .inputFluids("gtceu:hydrogen_sulfide 1000", "gtceu:zinc 144")
        .itemOutputs("gtocore:highly_reflective_mirror")
        .EUt(710000)
        .duration(240)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:lithium_niobate_nanoparticles_dust")
        .notConsumable("gtceu:hafnium_dust")
        .itemInputs("2x gtceu:lithium_dust", "gtceu:niobium_dust")
        .inputFluids("gtceu:oxygen 3000")
        .itemOutputs("6x gtceu:lithium_niobate_nanoparticles_dust")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(1200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:sodium_seaborgate_dust")
        .itemInputs("gtceu:seaborgium_dust", "6x gtceu:sodium_hydroxide_dust")
        .inputFluids("gtceu:fluorine 6000", "minecraft:water 1000")
        .outputFluids("gtceu:hydrofluoric_acid 6000")
        .itemOutputs("7x gtceu:sodium_seaborgate_dust")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:optical_wafer")
        .itemInputs("2x gtceu:francium_caesium_cadmium_bromide_dust", "gtocore:photon_carrying_wafer", "gtceu:glowstone_nanites")
        .inputFluids("gtceu:seaborgium_doped_nanotubes 144", "gtceu:carbon_nanotubes 144")
        .itemOutputs("gtocore:optical_wafer")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(400)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:seaborgium_doped_nanotubes")
        .itemInputs("gtceu:seaborgium_dust")
        .notConsumable("gtceu:rhenium_plate")
        .inputFluids("gtceu:methane 800", "gtceu:cycloparaphenylene 200")
        .outputFluids("gtceu:seaborgium_doped_nanotubes 144")
        .EUt(320000)
        .duration(390)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:quantum_dots")
        .itemInputs("gtceu:selenium_dust", "gtceu:cadmium_dust")
        .inputFluids("gtceu:stearic_acid 1000", "gtceu:tricotylphosphine 1000")
        .outputFluids("gtceu:quantum_dots 1000")
        .EUt(5000000)
        .duration(160)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:deglycerated_soap")
        .inputFluids("gtceu:soap 1000")
        .itemInputs("gtceu:salt_dust")
        .outputFluids("gtceu:deglycerated_soap 800", "gtceu:glycerol 200")
        .EUt(2000)
        .duration(160)

    gtr.chemical_reactor("gtocore:soap_1")
        .itemInputs("3x gtceu:sodium_hydroxide_dust")
        .inputFluids("gtceu:steam 2000", "gtceu:fish_oil 100")
        .outputFluids("gtceu:soap 1000")
        .EUt(2000)
        .duration(160)

    gtr.chemical_reactor("gtocore:soap_2")
        .itemInputs("3x gtceu:sodium_hydroxide_dust")
        .inputFluids("gtceu:steam 2000", "gtceu:seed_oil 100")
        .outputFluids("gtceu:soap 1000")
        .EUt(2000)
        .duration(160)

    gtr.chemical_reactor("gtocore:tricotylphosphine")
        .inputFluids("gtceu:octane 3000")
        .itemInputs("gtceu:phosphorus_dust")
        .outputFluids("gtceu:tricotylphosphine 1000")
        .EUt(2000)
        .duration(160)

    gtr.large_chemical_reactor("gtocore:cosmic_computing_mixture")
        .notConsumable("gtceu:vibranium_nanites")
        .inputFluids("gtceu:gluons 1000", "gtceu:heavy_quarks 1000", "gtceu:heavy_lepton_mixture 1000")
        .outputFluids("gtceu:cosmic_computing_mixture 3000")
        .EUt(24000000)
        .duration(100)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:aminated_fullerene")
        .itemInputs("gtceu:fullerene_dust")
        .inputFluids("gtceu:carbon_monoxide 4000", "minecraft:water 8000", "gtceu:tertbuthylcarbonylazide 4000")
        .outputFluids("gtceu:aminated_fullerene 1000", "gtceu:carbon_dioxide 8000", "gtceu:tert_butanol 4000")
        .EUt(30720)
        .duration(120)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:tertbuthylcarbonylazide")
        .itemInputs("33x gtceu:ditertbutyl_dicarbonate_dust", "8x gtceu:sodium_azide_dust", "2x gtceu:potassium_dust")
        .itemOutputs("2x gtceu:sodium_dust", "6x gtceu:potash_dust")
        .outputFluids("gtceu:tertbuthylcarbonylazide 2000")
        .EUt(480)
        .duration(110)

    gtr.chemical_reactor("gtocore:sodium_toluenesulfonate")
        .itemInputs("2x gtceu:salt_dust")
        .inputFluids("gtceu:sulfuric_acid 1000", "gtceu:toluene 1000")
        .outputFluids("gtceu:sodium_toluenesulfonate 1000", "gtceu:diluted_hydrochloric_acid 1000")
        .EUt(950)
        .duration(220)

    gtr.chemical_reactor("gtocore:tert_butanol")
        .notConsumable("gtceu:magnesium_chloride_dust")
        .itemInputs("gtceu:zeolite_sieving_pellets_dust")
        .inputFluids("gtceu:methane 1000", "gtceu:acetone 1000")
        .outputFluids("gtceu:tert_butanol 1000")
        .itemOutputs("gtceu:wet_zeolite_sieving_pellets_dust")
        .EUt(120)
        .duration(126)

    gtr.chemical_reactor("gtocore:ditertbutyl_dicarbonate_dust")
        .notConsumableFluid("gtceu:sodium_toluenesulfonate 1000")
        .inputFluids("gtceu:tert_butanol 2000", "gtceu:carbon_dioxide 2000")
        .outputFluids("minecraft:water 1000")
        .itemOutputs("33x gtceu:ditertbutyl_dicarbonate_dust")
        .EUt(480)
        .duration(260)

    gtr.chemical_reactor("gtocore:attuned_tengam_ingot")
        .itemInputs("gtceu:attuned_tengam_dust", "gtceu:magnetic_samarium_dust")
        .inputFluids("gtceu:infuscolium_plasma 144", "gtceu:nitrogen_plasma 1000")
        .itemOutputs("gtceu:attuned_tengam_ingot")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(1600)

    gtr.chemical_reactor("gtocore:bioware_printed_circuit_board")
        .itemInputs("gtocore:bioware_circuit_board", "32x gtceu:vanadium_gallium_foil")
        .inputFluids("gtceu:iron_iii_chloride 10000")
        .itemOutputs("gtocore:bioware_printed_circuit_board")
        .EUt(1920)
        .duration(2100)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)

    gtr.chemical_reactor("gtocore:bioware_printed_circuit_board1")
        .itemInputs("gtocore:bioware_circuit_board", "32x gtceu:vanadium_gallium_foil")
        .inputFluids("gtceu:sodium_persulfate 20000")
        .itemOutputs("gtocore:bioware_printed_circuit_board")
        .EUt(1920)
        .duration(2100)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)

    gtr.large_chemical_reactor("gtocore:unknownnutrientagar")
        .inputFluids("gtceu:unknowwater 4000", "gtceu:phthalic_acid 4000")
        .itemInputs("16x gtceu:salt_dust", "16x gtceu:meat_dust", "16x gtceu:agar_dust")
        .outputFluids("gtceu:unknownnutrientagar 8000")
        .EUt(1920)
        .duration(800)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)

    gtr.chemical_reactor("gtocore:uranium_sulfate_waste_solution")
        .itemInputs("gtceu:impure_uraninite_dust")
        .inputFluids("gtceu:sulfuric_acid 1000")
        .itemOutputs("gtceu:uraninite_dust")
        .outputFluids("gtceu:uranium_sulfate_waste_solution 1000")
        .EUt(120)
        .duration(200)

    gtr.chemical_reactor("gtocore:bismuth_tellurite_dust")
        .itemInputs("2x gtceu:bismuth_dust", "3x gtceu:tellurium_dust")
        .itemOutputs("5x gtceu:bismuth_tellurite_dust")
        .EUt(120)
        .duration(760)

    gtr.chemical_reactor("gtocore:prasiolite_dust")
        .itemInputs("5x gtceu:silicon_dust", "enderio:powdered_iron")
        .inputFluids("gtceu:oxygen 10000")
        .itemOutputs("gtceu:prasiolite_dust")
        .EUt(480)
        .duration(270)

    gtr.chemical_reactor("gtocore:dibismuthhydroborat_dust")
        .itemInputs("2x gtceu:bismuth_dust", "gtceu:boron_dust")
        .inputFluids("gtceu:hydrogen 1000")
        .itemOutputs("4x gtceu:dibismuthhydroborat_dust")
        .EUt(90)
        .duration(590)

    gtr.chemical_reactor("gtocore:acrylic_acid")
        .itemInputs("3x gtceu:sodium_hydroxide_dust")
        .inputFluids("gtceu:allyl_chloride 1000", "minecraft:water 1000", "gtceu:oxygen 1000")
        .outputFluids("gtceu:acrylic_acid 1000")
        .itemOutputs("2x gtceu:salt_dust")
        .EUt(120)
        .duration(200)

    gtr.chemical_reactor("gtocore:ethyl_acrylate")
        .inputFluids("gtceu:acrylic_acid 1000", "gtceu:ethanol 1000", "gtceu:sulfuric_acid 1000")
        .outputFluids("gtceu:ethyl_acrylate 1000", "gtceu:diluted_sulfuric_acid 1000")
        .EUt(120)
        .duration(600)

    gtr.large_chemical_reactor("gtocore:photoresist")
        .inputFluids("gtceu:ethyl_acrylate 1000", "gtceu:styrene 1000", "gtceu:titanium_tetrachloride 100")
        .outputFluids("gtceu:photoresist 1000")
        .EUt(1920)
        .duration(800)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.large_chemical_reactor("gtocore:trichloroflerane")
        .notConsumable("gtceu:ferrosilite_dust")
        .itemInputs("gtceu:flerovium_dust")
        .inputFluids("gtceu:hydrochloric_acid 3000")
        .outputFluids("gtceu:trichloroflerane 1000", "gtceu:hydrogen 3000")
        .EUt(7680)
        .duration(150)

    gtr.large_chemical_reactor("gtocore:cyclopentadienyl_titanium_trichloride_dust")
        .inputFluids("gtceu:titanium_tetrachloride 1000", "gtceu:propadiene 2000", "gtceu:acetylene 2000")
        .itemOutputs("23x gtceu:cyclopentadienyl_titanium_trichloride_dust")
        .outputFluids("gtceu:hydrochloric_acid 2000")
        .EUt(7680)
        .duration(780)

    gtr.large_chemical_reactor("gtocore:propadiene")
        .inputFluids("gtceu:butene 1000", "gtceu:propene")
        .outputFluids("gtceu:butane 1000", "gtceu:propadiene 1000")
        .EUt(480)
        .duration(2400)

    gtr.chemical_reactor("gtocore:lithiumthiinediselenide_dust")
        .inputFluids("gtceu:bromodihydrothiine 1000", "gtceu:butyl_lithium 2000")
        .itemInputs("2x gtceu:selenium_dust")
        .outputFluids("gtceu:bromobutane 2000")
        .itemOutputs("14x gtceu:lithiumthiinediselenide_dust")
        .EUt(30720)
        .duration(290)

    gtr.chemical_reactor("gtocore:butyl_lithium")
        .itemInputs("gtceu:lithium_dust")
        .inputFluids("gtceu:butane 1000")
        .outputFluids("gtceu:butyl_lithium 1000", "gtceu:hydrogen 1000")
        .EUt(480)
        .duration(150)

    gtr.large_chemical_reactor("gtocore:bromodihydrothiine")
        .inputFluids("gtceu:ethane 1000", "gtceu:chlorine 1000", "gtceu:dibromoacrolein 1000")
        .itemInputs("14x gtceu:sodium_thiosulfate_dust")
        .outputFluids("gtceu:bromodihydrothiine 1000", "gtceu:hydrogen 1000")
        .itemOutputs("4x gtceu:salt_dust", "14x gtceu:sodium_bisulfate_dust")
        .EUt(7680)
        .duration(400)

    gtr.large_chemical_reactor("gtocore:dibromoacrolein")
        .inputFluids("gtceu:formic_acid 2000", "minecraft:water 2000", "gtceu:bromine 2000")
        .outputFluids("gtceu:dibromoacrolein 1000", "gtceu:hydrogen 2000")
        .itemOutputs("12x gtceu:sodium_hydroxide_dust")
        .EUt(7680)
        .duration(360)

    gtr.chemical_reactor("gtocore:francium_carbide_dust")
        .itemInputs("2x gtceu:francium_dust")
        .inputFluids("gtceu:acetylene 1000")
        .itemOutputs("4x gtceu:francium_carbide_dust")
        .outputFluids("gtceu:hydrogen 2000")
        .EUt(480)
        .duration(260)

    gtr.chemical_reactor("gtocore:boron_francium_carbide_dust")
        .itemInputs("8x gtceu:francium_carbide_dust", "7x gtceu:boron_carbide_dust")
        .itemOutputs("15x gtceu:boron_francium_carbide_dust")
        .EUt(7680)
        .duration(900)

    gtr.large_chemical_reactor("gtocore:fullerene_doped_nanotubes")
        .itemInputs("gtceu:fullerene_dust")
        .notConsumable("gtceu:rhenium_plate")
        .inputFluids("gtceu:methane 14400", "gtceu:cycloparaphenylene 3600")
        .outputFluids("gtceu:fullerene_doped_nanotubes 18000")
        .EUt(320000)
        .duration(290)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:dimethylether")
        .notConsumable("gtceu:silicon_dioxide_dust")
        .inputFluids("gtceu:methanol 2000")
        .outputFluids("gtceu:dimethylether 1000", "minecraft:water 1000")
        .EUt(8000)
        .duration(160)

    gtr.chemical_reactor("gtocore:dimethoxyethane")
        .inputFluids("gtceu:dimethylether 1000", "gtceu:ethylene_oxide 1000")
        .outputFluids("gtceu:dimethoxyethane 1000")
        .EUt(2000)
        .duration(160)

    gtr.chemical_reactor("gtocore:lithium_cyclopentadienide")
        .inputFluids("gtceu:butyl_lithium 1000", "gtceu:dimethoxyethane 500", "gtceu:cyclopentadiene 1000")
        .outputFluids("gtceu:lithium_cyclopentadienide 1000", "gtceu:butane 1000")
        .EUt(10000)
        .duration(460)

    gtr.large_chemical_reactor("gtocore:californium_trichloride_dust")
        .notConsumable("gtceu:ferrosilite_dust")
        .itemInputs("gtceu:californium_dust")
        .inputFluids("gtceu:hydrochloric_acid 6000")
        .outputFluids("gtceu:hydrogen 3000")
        .itemOutputs("4x gtceu:californium_trichloride_dust")
        .EUt(7680)
        .duration(150)

    gtr.chemical_reactor("gtocore:californium_cyclopentadienide")
        .inputFluids("gtceu:lithium_cyclopentadienide 3000")
        .itemInputs("4x gtceu:californium_trichloride_dust")
        .outputFluids("gtceu:californium_cyclopentadienide 1000")
        .EUt(2000000)
        .duration(160)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:sodium_hypochlorite_dust")
        .circuit(1)
        .itemInputs("6x gtceu:sodium_hydroxide_dust")
        .inputFluids("gtceu:chlorine 2000")
        .itemOutputs("3x gtceu:sodium_hypochlorite_dust", "2x gtceu:salt_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(120)
        .duration(80)

    gtr.chemical_reactor("gtocore:ethylanthraquinone")
        .itemInputs("15x gtceu:phthalic_anhydride_dust")
        .inputFluids("gtceu:ethylbenzene 1000")
        .outputFluids("gtceu:ethylanthraquinone 1000", "minecraft:water 1000")
        .EUt(480)
        .duration(800)

    gtr.chemical_reactor("gtocore:ethylanthrahydroquinone")
        .inputFluids("gtceu:ethylanthraquinone 1000", "gtceu:hydrogen 2000")
        .outputFluids("gtceu:ethylanthrahydroquinone 1000")
        .EUt(30)
        .duration(200)

    gtr.chemical_reactor("gtocore:hydrogen_peroxide")
        .notConsumableFluid("gtceu:anthracene 1000")
        .inputFluids("gtceu:ethylanthrahydroquinone 1000", "gtceu:oxygen 2000")
        .outputFluids("gtceu:hydrogen_peroxide 1000", "gtceu:ethylanthraquinone 1000")
        .EUt(480)
        .duration(600)

    gtr.chemical_reactor("gtocore:sodium_perchlorate_dust")
        .inputFluids("gtceu:hydrogen_peroxide 1000")
        .itemInputs("5x gtceu:sodium_chlorate_dust")
        .itemOutputs("6x gtceu:sodium_perchlorate_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(120)
        .duration(480)

    gtr.chemical_reactor("gtocore:silver_chloride_dust")
        .itemInputs("gtceu:silver_dust")
        .inputFluids("gtceu:chlorine 1000")
        .itemOutputs("2x gtceu:silver_chloride_dust")
        .EUt(120)
        .duration(80)

    gtr.chemical_reactor("gtocore:silver_oxide_dust")
        .notConsumable("gtceu:sodium_hydroxide_dust")
        .itemInputs("4x gtceu:silver_chloride_dust")
        .inputFluids("minecraft:water 1000")
        .itemOutputs("3x gtceu:silver_oxide_dust")
        .outputFluids("gtceu:diluted_hydrochloric_acid 2000")
        .EUt(30)
        .duration(100)

    gtr.large_chemical_reactor("gtocore:silver_perchlorate_dust")
        .itemInputs("3x gtceu:silver_oxide_dust", "12x gtceu:sodium_perchlorate_dust")
        .inputFluids("gtceu:hydrochloric_acid 1000")
        .itemOutputs("12x gtceu:silver_perchlorate_dust", "3x gtceu:sodium_oxide_dust")
        .outputFluids("gtceu:diluted_hydrochloric_acid 1000")
        .EUt(480)
        .duration(350)

    gtr.chemical_reactor("gtocore:phenylsodium")
        .itemInputs("2x gtceu:sodium_dust")
        .inputFluids("gtceu:fluoro_benzene 1000")
        .outputFluids("gtceu:phenylsodium 1000")
        .itemOutputs("2x gtceu:sodium_fluoride_dust")
        .EUt(480)
        .duration(210)

    gtr.chemical_reactor("gtocore:tetraethylammonium_bromide")
        .inputFluids("gtceu:ethylene 4000", "gtceu:ammonia 1000", "gtceu:hydrobromic_acid 1000")
        .outputFluids("gtceu:tetraethylammonium_bromide 1000")
        .EUt(1920)
        .duration(200)

    gtr.chemical_reactor("gtocore:difluoroaniline")
        .itemInputs("8x gtceu:sodium_fluoride_dust")
        .inputFluids("gtceu:hydrogen 1000", "gtceu:dichlorobenzene 1000", "gtceu:nitrogen 1000")
        .outputFluids("gtceu:difluoroaniline 2000")
        .itemOutputs("8x gtceu:salt_dust")
        .EUt(7680)
        .duration(200)

    gtr.large_chemical_reactor("gtocore:succinaldehyde")
        .itemInputs("14x gtceu:succinic_acid_dust", "4x gtceu:lithium_aluminium_hydride_dust")
        .outputFluids("gtceu:succinaldehyde 1000", "minecraft:water 2000")
        .itemOutputs("gtceu:lithium_dust", "gtceu:aluminium_dust")
        .EUt(1920)
        .duration(600)

    gtr.chemical_reactor("gtocore:n_difluorophenylpyrrole")
        .notConsumable("gtceu:phosphorus_pentoxide_dust")
        .inputFluids("gtceu:succinaldehyde 1000", "gtceu:difluoroaniline 1000")
        .outputFluids("gtceu:n_difluorophenylpyrrole 1000", "minecraft:water 2000")
        .EUt(480)
        .duration(180)

    gtr.large_chemical_reactor("gtocore:photopolymer")
        .itemInputs("69x gtceu:cyclopentadienyl_titanium_trichloride_dust", "42x gtceu:ice_dust", "12x gtceu:silver_perchlorate_dust")
        .inputFluids("gtceu:phenylsodium 8000", "gtceu:silver_tetrafluoroborate 2000", "gtceu:hydrochloric_acid 2000", "gtceu:n_difluorophenylpyrrole 6000", "gtceu:tetraethylammonium_bromide 2000")
        .itemOutputs("8x gtceu:silver_chloride_dust", "4x gtceu:sodium_bromide_dust")
        .outputFluids("gtceu:salt_water 6000", "gtceu:photopolymer 8000")
        .EUt(30720)
        .duration(340)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:iodine_monochloride")
        .itemInputs("gtceu:iodine_dust")
        .inputFluids("gtceu:chlorine 1000")
        .outputFluids("gtceu:iodine_monochloride 1000")
        .EUt(120)
        .duration(260)

    gtr.chemical_reactor("gtocore:dimethylnaphthalene")
        .inputFluids("gtceu:methanol 2000", "gtceu:naphthalene 1000")
        .outputFluids("gtceu:dimethylnaphthalene 1000", "minecraft:water 2000")
        .EUt(120)
        .duration(200)

    gtr.large_chemical_reactor("gtocore:acetylating_reagent")
        .itemInputs("6x gtceu:magnesium_chloride_dust")
        .inputFluids("gtceu:bromine 2000", "gtceu:trimethylchlorosilane 1000", "gtceu:acetylene 3000")
        .outputFluids("gtceu:hydrochloric_acid 3000", "gtceu:chlorine 2000", "gtceu:acetylating_reagent 1000")
        .EUt(480)
        .duration(350)

    gtr.large_chemical_reactor("gtocore:dihydroiodotetracene")
        .notConsumable("gtceu:rhodium_rhenium_naquadah_catalyst_dust")
        .itemInputs("12x gtceu:bromo_succinimide_dust")
        .inputFluids("gtceu:iodine_monochloride 1000", "gtceu:acetylating_reagent 1000", "gtceu:dimethylnaphthalene 1000", "gtceu:chlorine 2000")
        .itemOutputs("6x gtceu:magnesium_chloride_bromide_dust", "12x gtceu:succinimide_dust")
        .outputFluids("gtceu:dihydroiodotetracene 1000", "gtceu:trimethylchlorosilane 1000", "gtceu:hydrobromic_acid 1000")
        .EUt(122880)
        .duration(350)

    gtr.chemical_reactor("gtocore:isopropyl_alcohol")
        .notConsumable("gtceu:tungstate_dust")
        .notConsumable("gtceu:sodium_seaborgate_dust")
        .inputFluids("gtceu:propene 1000", "minecraft:water 1000")
        .outputFluids("gtceu:isopropyl_alcohol 1000")
        .EUt(480)
        .duration(400)

    gtr.large_chemical_reactor("gtocore:dichlorodicyanobenzoquinone")
        .inputFluids("gtceu:hydrogen_cyanide 2000", "gtceu:chlorine 10000", "gtceu:phenol 1000", "gtceu:oxygen 1000")
        .outputFluids("gtceu:diluted_hydrochloric_acid 8000", "gtceu:dichlorodicyanobenzoquinone 1000")
        .EUt(30720)
        .duration(250)

    gtr.chemical_reactor("gtocore:dichlorodicyanobenzoquinone_1")
        .inputFluids("gtceu:hydrogen_peroxide 1000", "gtceu:dichlorodicyanohydroquinone 1000")
        .outputFluids("minecraft:water 2000", "gtceu:dichlorodicyanobenzoquinone 1000")
        .EUt(480)
        .duration(250)

    gtr.large_chemical_reactor("gtocore:tetracene_dust")
        .notConsumable("gtceu:blacklight")
        .inputFluids("gtceu:isopropyl_alcohol 1000", "gtceu:dichlorodicyanobenzoquinone 2000", "gtceu:dihydroiodotetracene 2000")
        .itemOutputs("60x gtceu:tetracene_dust", "2x gtceu:iodine_dust")
        .outputFluids("gtceu:dichlorodicyanohydroquinone 2000", "gtceu:acetone 1000")
        .EUt(491520)
        .duration(260)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:nitrogen_pentoxide")
        .inputFluids("gtceu:ozone 1000", "gtceu:nitrogen_dioxide 6000")
        .outputFluids("gtceu:nitrogen_pentoxide 3000")
        .EUt(480)
        .duration(240)

    gtr.chemical_reactor("gtocore:sodium_azanide_dust")
        .itemInputs("gtceu:sodium_dust")
        .inputFluids("gtceu:ammonia 1000")
        .outputFluids("gtceu:hydrogen 1000")
        .itemOutputs("4x gtceu:sodium_azanide_dust")
        .EUt(120)
        .duration(110)

    gtr.chemical_reactor("gtocore:sodium_azide_dust")
        .itemInputs("8x gtceu:sodium_azanide_dust")
        .inputFluids("gtceu:nitrogen_dioxide 1000")
        .outputFluids("gtceu:ammonia 1000")
        .itemOutputs("4x gtceu:sodium_azide_dust", "3x gtceu:sodium_hydroxide_dust")
        .EUt(480)
        .duration(170)

    gtr.chemical_reactor("gtocore:ethylamine")
        .inputFluids("gtceu:ammonia 1000", "gtceu:ethylene 1000")
        .notConsumable("gtceu:sodium_azanide_dust")
        .outputFluids("gtceu:ethylamine 1000")
        .EUt(480)
        .duration(130)

    gtr.chemical_reactor("gtocore:isochloropropane")
        .inputFluids("gtceu:propane 1000", "gtceu:chlorine 2000")
        .outputFluids("gtceu:isochloropropane 1000", "gtceu:hydrochloric_acid 1000")
        .EUt(30)
        .duration(100)

    gtr.large_chemical_reactor("gtocore:rhenium_hassium_thallium_isophtaloylbisdiethylthiourea_hexaf_dust")
        .itemInputs("2x gtceu:thallium_chloride_dust", "5x gtceu:hassium_chloride_dust", "6x gtceu:rhenium_chloride_dust")
        .inputFluids("gtceu:hexafluorophosphoric_acid 1000", "gtceu:isophthaloylbis 3000")
        .itemOutputs("125x gtceu:rhenium_hassium_thallium_isophtaloylbisdiethylthiourea_hexaf_dust")
        .outputFluids("gtceu:hydrochloric_acid 7000", "gtceu:chlorine 3000")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.chemical_reactor("gtocore:thallium_chloride_dust")
        .itemInputs("gtceu:thallium_dust")
        .inputFluids("gtceu:hydrochloric_acid 1000")
        .itemOutputs("2x gtceu:thallium_chloride_dust")
        .outputFluids("gtceu:hydrogen 1000")
        .EUt(120)
        .duration(100)

    gtr.large_chemical_reactor("gtocore:isophthaloylbis")
        .inputFluids("gtceu:phenylenedioxydiacetic_acid 1000", "gtceu:thionyl_chloride 2000", "gtceu:diethylthiourea 2000")
        .outputFluids("gtceu:isophthaloylbis 1000", "gtceu:sulfur_dioxide 2000", "gtceu:hydrochloric_acid 4000")
        .EUt(122880)
        .duration(250)

    gtr.large_chemical_reactor("gtocore:diethylthiourea")
        .inputFluids("gtceu:hydrochloric_acid 1000", "gtceu:ethylamine 2000", "gtceu:sodium_thiocyanate 1000")
        .outputFluids("gtceu:diethylthiourea 1000", "gtceu:ammonia 1000")
        .itemOutputs("2x gtceu:salt_dust")
        .EUt(30720)
        .duration(210)

    gtr.chemical_reactor("gtocore:sodium_thiocyanate")
        .itemInputs("gtceu:sulfur_dust")
        .inputFluids("gtceu:sodium_cyanide 1000")
        .outputFluids("gtceu:sodium_thiocyanate 1000")
        .EUt(120)
        .duration(100)

    gtr.chemical_reactor("gtocore:thionyl_chloride")
        .itemInputs("gtceu:sulfur_dust")
        .inputFluids("gtceu:sulfur_trioxide 1000", "gtceu:chlorine 2000")
        .outputFluids("gtceu:thionyl_chloride 1000", "gtceu:sulfur_dioxide 1000")
        .EUt(120)
        .duration(100)

    gtr.large_chemical_reactor("gtocore:phenylenedioxydiacetic_acid")
        .inputFluids("minecraft:water 1000", "gtceu:hydrogen_peroxide 1000", "gtceu:phenol 1000", "gtceu:ethenone 2000", "gtceu:chlorine 4000")
        .outputFluids("gtceu:phenylenedioxydiacetic_acid 1000", "gtceu:hydrochloric_acid 4000")
        .EUt(122880)
        .duration(320)

    gtr.large_chemical_reactor("gtocore:hexafluorophosphoric_acid")
        .inputFluids("gtceu:antimony_pentafluoride 1000", "gtceu:phosphorus_trichloride 1000", "gtceu:hydrofluoric_acid 1000")
        .outputFluids("gtceu:hexafluorophosphoric_acid 1000")
        .itemOutputs("4x gtceu:antimony_trichloride_dust")
        .EUt(30720)
        .duration(280)

    gtr.chemical_reactor("gtocore:phosphorus_trichloride")
        .itemInputs("gtceu:phosphorus_dust")
        .inputFluids("gtceu:chlorine 3000")
        .outputFluids("gtceu:phosphorus_trichloride 1000")
        .EUt(30)
        .duration(60)

    gtr.chemical_reactor("gtocore:antimony_pentafluoride")
        .itemInputs("4x gtceu:antimony_trifluoride_dust")
        .inputFluids("gtceu:fluorine 2000")
        .outputFluids("gtceu:antimony_pentafluoride 1000")
        .EUt(480)
        .duration(100)

    gtr.chemical_reactor("gtocore:antimony_trifluoride_dust_a")
        .itemInputs("4x gtceu:antimony_trichloride_dust")
        .inputFluids("gtceu:hydrofluoric_acid 3000")
        .outputFluids("gtceu:hydrochloric_acid 3000")
        .itemOutputs("4x gtceu:antimony_trifluoride_dust")
        .EUt(480)
        .duration(210)

    gtr.chemical_reactor("gtocore:carbon_tetrachloride")
        .circuit(4)
        .itemInputs("gtceu:carbon_dust")
        .inputFluids("gtceu:chlorine 4000")
        .outputFluids("gtceu:carbon_tetrachloride 1000")
        .EUt(120)
        .duration(200)

    gtr.chemical_reactor("gtocore:actinium_oxalate_dust")
        .itemInputs("gtceu:actinium_dust")
        .inputFluids("gtceu:oxalic_acid 4000")
        .itemOutputs("13x gtceu:actinium_oxalate_dust")
        .EUt(1920)
        .duration(200)

    gtr.large_chemical_reactor("gtocore:cosmic_superconductor")
        .itemInputs("125x gtceu:rhenium_hassium_thallium_isophtaloylbisdiethylthiourea_hexaf_dust", "39x gtceu:actinium_superhydride_dust", "14x gtceu:charged_caesium_cerium_cobalt_indium_dust")
        .inputFluids("gtceu:light_quarks 10000", "gtceu:free_alpha_gas 1000")
        .outputFluids("gtceu:cosmic_superconductor 10000")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(600)
        .cleanroom(GTOCleanroomType.LAW_CLEANROOM)

    gtr.large_chemical_reactor("gtocore:charged_lepton_trap_crystal")
        .notConsumable("gtceu:starmetal_nanites")
        .itemInputs("gtocore:lepton_trap_crystal", "2x gtceu:small_vibranium_dust")
        .inputFluids("gtceu:free_electron_gas 1000", "gtceu:heavy_lepton_mixture 1000")
        .itemOutputs("gtocore:charged_lepton_trap_crystal")
        .EUt(491520)
        .duration(240)
        .cleanroom(GTOCleanroomType.LAW_CLEANROOM)

    gtr.large_chemical_reactor("gtocore:glycerol_a")
        .circuit(1)
        .notConsumable("gtceu:soda_ash_dust")
        .notConsumableFluid("gtceu:carbon_dioxide 10000")
        .itemInputs("3x gtceu:sodium_hydroxide_dust")
        .inputFluids("gtceu:epichlorohydrin 1000", "minecraft:water 2000")
        .outputFluids("gtceu:glycerol 1000", "gtceu:salt_water 1000")
        .EUt(7680)
        .duration(150)

    gtr.large_chemical_reactor("gtocore:toluene_diisocyanate")
        .inputFluids("gtceu:nitric_acid 2000", "gtceu:phosgene 2000", "gtceu:toluene 1000", "gtceu:hydrogen 1000")
        .outputFluids("gtceu:toluene_diisocyanate 2000", "gtceu:hydrochloric_acid 4000", "minecraft:water 6000")
        .EUt(480)
        .duration(130)

    gtr.chemical_reactor("gtocore:polyurethane")
        .inputFluids("gtceu:oxygen 1000", "gtceu:ethyleneglycol 4000", "gtceu:toluene_diisocyanate 1000")
        .outputFluids("gtceu:polyurethane 1000", "minecraft:water 7000")
        .EUt(480)
        .duration(110)

    gtr.large_chemical_reactor("gtocore:mutated_living_solder")
        .notConsumable("gtceu:gravi_star")
        .itemInputs("16x gtocore:biological_cells", "gtceu:quantum_star")
        .inputFluids("gtceu:helium_plasma 2000", "gtceu:oxygen_plasma 2000", "gtceu:tin 2000", "gtceu:carbon 2000", "gtceu:beryllium 2000")
        .outputFluids("gtceu:mutated_living_solder 2000")
        .itemOutputs("4x gtceu:tiny_nether_star_dust")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(1200)

    gtr.large_chemical_reactor("gtocore:hydrazine")
        .inputFluids("gtceu:hydrogen_peroxide 1000", "gtceu:ammonia 2000")
        .outputFluids("gtceu:hydrazine 1000", "minecraft:water 1000")
        .EUt(30)
        .duration(320)

    gtr.large_chemical_reactor("gtocore:stellar_energy_rocket_fuel")
        .itemInputs("gtceu:enriched_naquadah_dust")
        .inputFluids("gtceu:rocket_fuel_cn3h7o3 2000", "gtceu:explosivehydrazine 3000", "gtceu:nitrobenzene 8000", "gtceu:dinitrogen_tetroxide 6000", "gtceu:kerosene 4000")
        .itemInputs("2x gtceu:hmxexplosive_dust")
        .itemOutputs("gtceu:naquadah_dust")
        .outputFluids("gtceu:stellar_energy_rocket_fuel 5000")
        .EUt(122880)
        .duration(120)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)

    gtr.chemical_reactor("gtocore:hmxexplosive_dust")
        .notConsumableFluid("gtceu:acetic_anhydride 1000")
        .inputFluids("gtceu:fuming_nitric_acid 2000")
        .itemInputs("22x gtceu:hexamethylenetetramine_dust")
        .itemOutputs("gtceu:hmxexplosive_dust")
        .EUt(1024)
        .duration(20)

    gtr.chemical_reactor("gtocore:fuming_nitric_acid")
        .inputFluids("gtceu:nitrogen_dioxide 1000", "gtceu:nitric_acid 1000")
        .outputFluids("gtceu:fuming_nitric_acid 1000")
        .EUt(120)
        .duration(200)

    gtr.chemical_reactor("gtocore:ammonium_chloride_dust")
        .inputFluids("gtceu:hydrochloric_acid 1000", "gtceu:ammonia 1000")
        .itemOutputs("6x gtceu:ammonium_chloride_dust")
        .EUt(30)
        .duration(120)

    gtr.chemical_reactor("gtocore:zirconium_hafnium_chloride")
        .itemInputs("6x gtceu:zircon_dust")
        .inputFluids("gtceu:chlorine 8000")
        .outputFluids("gtceu:zirconium_hafnium_chloride 1000", "gtceu:zircon_chlorinating_residue 1000")
        .EUt(120)
        .duration(120)

    gtr.chemical_reactor("gtocore:zirconiu_hafnium_oxychloride")
        .inputFluids("gtceu:zirconium_hafnium_chloride 1000", "minecraft:water 1000")
        .outputFluids("gtceu:zirconiu_hafnium_oxychloride 1000", "gtceu:diluted_hydrochloric_acid 2000")
        .EUt(480)
        .duration(100)

    gtr.large_chemical_reactor("gtocore:zirconium_oxide_dust")
        .itemInputs("36x gtceu:ammonium_chloride_dust", "9x gtceu:potassium_hydroxide_dust", "10x gtceu:hematite_dust")
        .inputFluids("gtceu:zirconiu_hafnium_oxychloride 3000", "gtceu:sulfur_trioxide 3000", "gtceu:hydrogen_peroxide 6000")
        .itemOutputs("21x gtceu:potassium_sulfate_dust", "3x gtceu:zirconium_oxide_dust")
        .chancedOutput("3x gtceu:hafnium_oxide_dust", 8000, 0)
        .outputFluids("gtceu:ammonia 6000", "gtceu:iron_iii_chloride 4000")
        .EUt(1920)
        .duration(100)

    gtr.chemical_reactor("gtocore:hafnium_chloride_dust")
        .itemInputs("3x gtceu:hafnium_oxide_dust", "gtceu:carbon_dust")
        .inputFluids("gtceu:chlorine 4000")
        .itemOutputs("5x gtceu:hafnium_chloride_dust")
        .outputFluids("gtceu:carbon_dioxide 1000")
        .EUt(120)
        .duration(150)

    gtr.chemical_reactor("gtocore:butane_1_4_diol")
        .notConsumable("gtceu:molybdenum_trioxide_dust")
        .itemInputs("3x gtceu:tellurium_oxide_dust")
        .inputFluids("gtceu:butane 1000")
        .outputFluids("gtceu:butane_1_4_diol 1000")
        .itemOutputs("gtceu:tellurium_dust")
        .EUt(1920)
        .duration(20)

    gtr.chemical_reactor("gtocore:gammabutyrolactone")
        .notConsumable("enderio:powdered_copper")
        .inputFluids("gtceu:butane_1_4_diol 1000")
        .outputFluids("gtceu:gammabutyrolactone 1000", "gtceu:hydrogen 4000")
        .EUt(1920)
        .duration(80)

    gtr.chemical_reactor("gtocore:methylamine")
        .circuit(1)
        .inputFluids("gtceu:ammonia 1000", "gtceu:methanol 1000")
        .outputFluids("gtceu:methylamine 1000", "minecraft:water 1000")
        .EUt(1920)
        .duration(80)

    gtr.chemical_reactor("gtocore:nmethylpyrolidone")
        .inputFluids("gtceu:gammabutyrolactone 1000", "gtceu:methylamine 1000")
        .outputFluids("gtceu:nmethylpyrolidone 1000", "minecraft:water 1000")
        .EUt(7680)
        .duration(120)

    gtr.chemical_reactor("gtocore:p_nitroaniline")
        .notConsumableFluid("gtceu:acetic_anhydride 1000")
        .inputFluids("gtceu:aniline 1000", "gtceu:nitration_mixture 2000")
        .outputFluids("gtceu:p_nitroaniline 1000", "gtceu:diluted_sulfuric_acid 1000")
        .EUt(1920)
        .duration(150)

    gtr.large_chemical_reactor("gtocore:p_phenylenediamine_dust")
        .notConsumable("gtceu:palladium_dust")
        .inputFluids("gtceu:nitrogen_dioxide 100", "gtceu:hydrogen 6000", "gtceu:p_nitroaniline 1000")
        .outputFluids("minecraft:water 2000")
        .itemOutputs("16x gtceu:p_phenylenediamine_dust")
        .EUt(122880)
        .duration(60)

    gtr.chemical_reactor("gtocore:terephthalicacid")
        .notConsumable("gtceu:cadmium_dust")
        .notConsumable("gtceu:sodium_bisulfate_dust")
        .notConsumableFluid("gtceu:sulfuric_acid 1000")
        .inputFluids("gtceu:phthalic_acid 1000")
        .outputFluids("gtceu:terephthalicacid 1000")
        .EUt(480)
        .duration(800)

    gtr.chemical_reactor("gtocore:dimethylterephthalate")
        .inputFluids("gtceu:terephthalicacid 1000", "gtceu:methanol 2000", "gtceu:sulfuric_acid 2000")
        .outputFluids("gtceu:dimethylterephthalate 1000", "gtceu:diluted_sulfuric_acid 2000")
        .EUt(480)
        .duration(210)

    gtr.large_chemical_reactor("gtocore:terephthaloyl_chloride_dust")
        .inputFluids("gtceu:thionyl_chloride 20000", "gtceu:dimethylterephthalate 5000", "gtceu:carbon_dioxide 6000")
        .itemOutputs("64x gtceu:terephthaloyl_chloride_dust", "48x gtceu:terephthaloyl_chloride_dust")
        .outputFluids("gtceu:diluted_hydrochloric_acid 20000", "gtceu:sulfur_dioxide 20000")
        .EUt(1920)
        .duration(240)

    gtr.large_chemical_reactor("gtocore:liquidcrystalkevlar")
        .itemInputs("gtceu:calcium_chloride_dust", "9x gtceu:terephthaloyl_chloride_dust", "9x gtceu:p_phenylenediamine_dust")
        .inputFluids("gtceu:nmethylpyrolidone 1000")
        .outputFluids("gtceu:liquidcrystalkevlar 9000")
        .EUt(524288)
        .duration(160)

    gtr.chemical_reactor("gtocore:calcium_chloride_dust")
        .itemInputs("gtceu:calcium_dust")
        .inputFluids("gtceu:chlorine 2000")
        .itemOutputs("3x gtceu:calcium_chloride_dust")
        .EUt(30)
        .duration(80)

    gtr.large_chemical_reactor("gtocore:iridium_chloride_dust")
        .circuit(24)
        .itemInputs("gtceu:iridium_dust")
        .inputFluids("gtceu:chlorine 3000")
        .itemOutputs("4x gtceu:iridium_chloride_dust")
        .EUt(30720)
        .duration(800)

    gtr.large_chemical_reactor("gtocore:titanium_trifluoride_dust")
        .circuit(24)
        .itemInputs("gtceu:titanium_dust")
        .inputFluids("gtceu:fluorine 3000")
        .itemOutputs("4x gtceu:titanium_trifluoride_dust")
        .EUt(30720)
        .duration(600)

    gtr.large_chemical_reactor("gtocore:barium_sulfide_dust")
        .circuit(24)
        .itemInputs("6x gtceu:barite_dust")
        .inputFluids("gtceu:hydrogen 4000")
        .itemOutputs("2x gtceu:barium_sulfide_dust")
        .outputFluids("minecraft:water 4000")
        .EUt(30720)
        .duration(400)

    gtr.large_chemical_reactor("gtocore:aluminium_sulfite_dust")
        .circuit(24)
        .itemInputs("2x gtceu:aluminium_dust")
        .inputFluids("gtceu:sulfuric_acid 3000")
        .itemOutputs("14x gtceu:aluminium_sulfite_dust")
        .outputFluids("minecraft:water 3000")
        .EUt(30720)
        .duration(400)

    gtr.chemical_reactor("gtocore:potassium_bromide_dust")
        .itemInputs("gtceu:potassium_dust")
        .inputFluids("gtceu:bromine 1000")
        .itemOutputs("2x gtceu:potassium_bromide_dust")
        .EUt(120)
        .duration(160)

    gtr.chemical_reactor("gtocore:sodium_hydroxide_dust")
        .itemInputs("gtceu:sodium_dust")
        .inputFluids("minecraft:water 1000")
        .itemOutputs("3x gtceu:sodium_hydroxide_dust")
        .outputFluids("gtceu:hydrogen 1000")
        .EUt(30)
        .duration(60)

    gtr.chemical_reactor("gtocore:potassium_hydroxide_dust")
        .itemInputs("gtceu:potassium_dust")
        .inputFluids("minecraft:water 1000")
        .itemOutputs("3x gtceu:potassium_hydroxide_dust")
        .outputFluids("gtceu:hydrogen 1000")
        .EUt(30)
        .duration(60)

    gtr.chemical_reactor("gtocore:tungsten_dust")
        .inputFluids("gtceu:hydrogen 6000")
        .itemInputs("4x gtceu:tungsten_trioxide_dust")
        .outputFluids("minecraft:water 3000")
        .itemOutputs("gtceu:tungsten_dust")
        .EUt(120)
        .duration(60)

    gtr.chemical_reactor("gtocore:tungsten_trioxide_dust")
        .itemInputs("2x gtceu:tungsten_carbide_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("4x gtceu:tungsten_trioxide_dust")
        .outputFluids("gtceu:carbon_monoxide 1000")
        .EUt(480)
        .duration(200)

    gtr.chemical_reactor("gtocore:germanium_dioxide_dust")
        .itemInputs("gtceu:germanium_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("3x gtceu:germanium_dioxide_dust")
        .EUt(120)
        .duration(400)

    gtr.large_chemical_reactor("gtocore:bismuth_nitrate_solution")
        .itemInputs("gtceu:bismuth_dust")
        .inputFluids("gtceu:nitric_acid 6000")
        .outputFluids("gtceu:bismuth_nitrate_solution 1000", "gtceu:nitrogen_dioxide 3000", "minecraft:water 2000")
        .EUt(30)
        .duration(350)

    gtr.chemical_reactor("gtocore:sodium_ethylxanthate_dust")
        .itemInputs("9x gtceu:sodium_ethylate_dust")
        .inputFluids("gtceu:ethanol 1000", "gtceu:carbon_disulfide 1000")
        .itemOutputs("12x gtceu:sodium_ethylxanthate_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(40)

    gtr.chemical_reactor("gtocore:potassium_ethylxanthate_dust")
        .itemInputs("3x gtceu:potassium_ethylate_dust")
        .inputFluids("gtceu:carbon_disulfide 1000")
        .itemOutputs("12x gtceu:potassium_ethylxanthate_dust")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(40)

    gtr.large_chemical_reactor("gtocore:potassium_ethylate_dust")
        .circuit(2)
        .itemInputs("3x gtceu:potash_dust", "5x gtceu:quicklime_dust")
        .inputFluids("gtceu:carbon_dioxide 1000", "minecraft:water 5000")
        .itemOutputs("6x gtceu:potassium_ethylate_dust", "5x gtceu:high_purity_calcium_carbonate_dust")
        .EUt(GTValues.VA[GTValues.MV])
        .duration(100)

    gtr.chemical_reactor("gtocore:potash_dust")
        .circuit(1)
        .itemInputs("2x gtceu:potassium_dust")
        .inputFluids("gtceu:oxygen 1000")
        .itemOutputs("3x gtceu:potash_dust")
        .EUt(7)
        .duration(120)

    gtr.chemical_reactor("gtocore:selenium_oxide_dust")
        .itemInputs("3x gtceu:selenium_oxide_dust")
        .inputFluids("gtceu:sulfur_dioxide 2000")
        .itemOutputs("gtceu:selenium_dust")
        .outputFluids("gtceu:sulfur_trioxide 2000")
        .EUt(GTValues.VA[GTValues.MV])
        .duration(260)

    gtr.chemical_reactor("gtocore:nitrated_triniite_compound_solution")
        .itemInputs("36x gtceu:sodium_hydroxide_dust")
        .inputFluids("gtceu:nitrated_triniite_compound_solution 2000")
        .itemOutputs("29x gtceu:actinium_trinium_hydroxides_dust", "12x gtceu:sodium_sulfide_dust")
        .outputFluids("gtceu:residual_triniite_solution 2000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(190)

    gtr.chemical_reactor("gtocore:ethylene_sulfide")
        .itemInputs("7x gtceu:phosphorus_pentasulfide_dust")
        .inputFluids("gtceu:acetyl_chloride 5000", "gtceu:succinaldehyde 5000")
        .itemOutputs("7x gtceu:phosphorus_pentoxide_dust")
        .outputFluids("gtceu:ethylene_sulfide 5000", "gtceu:diluted_hydrochloric_acid 10000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(210)

    gtr.chemical_reactor("gtocore:acetyl_chloride")
        .inputFluids("gtceu:ethenone 1000", "gtceu:hydrochloric_acid 1000")
        .outputFluids("gtceu:acetyl_chloride 1000")
        .EUt(GTValues.VA[GTValues.MV])
        .duration(160)

    gtr.large_chemical_reactor("gtocore:ethyl_trifluoroacetate")
        .inputFluids("gtceu:hydrofluoric_acid 3000", "gtceu:acetyl_chloride 1000", "gtceu:ethanol 1000")
        .outputFluids("gtceu:ethyl_trifluoroacetate 1000", "gtceu:hydrogen 6000", "gtceu:hydrochloric_acid 1000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(230)

    gtr.chemical_reactor("gtocore:trifluoroacetic_phosphate_ester_dust")
        .itemInputs("9x gtceu:sodium_ethylate_dust")
        .inputFluids("gtceu:hydrochloric_acid 1000", "gtceu:ethylene_sulfide 1000", "gtceu:ethyl_trifluoroacetate 1000")
        .itemOutputs("2x gtceu:salt_dust", "4x gtceu:trifluoroacetic_phosphate_ester_dust")
        .outputFluids("gtceu:ethanol 2000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(220)

    gtr.large_chemical_reactor("gtocore:saturated_fullerene_sieving_matrix")
        .itemInputs("gtocore:saturated_fullerene_sieving_matrix")
        .inputFluids("gtceu:krypton_difluoride 16000", "gtceu:fluoroantimonic_acid 8000")
        .itemOutputs("32x gtceu:antimony_trifluoride_dust", "50x gtceu:fluorocarborane_dust","gtceu:fullerene_dust")
        .outputFluids("gtceu:krypton 16000", "gtceu:heavily_fluorinated_trinium_solution 8000")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(180)

    gtr.chemical_reactor("gtocore:krypton_difluoride")
        .notConsumable("gtceu:blacklight")
        .inputFluids("gtceu:fluorine 2000", "gtceu:krypton 1000")
        .outputFluids("gtceu:krypton_difluoride 1000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(190)

    gtr.chemical_reactor("gtocore:fluorite_dust")
        .itemInputs("gtceu:calcium_dust")
        .inputFluids("gtceu:fluorine 2000")
        .itemOutputs("3x gtceu:fluorite_dust")
        .EUt(GTValues.VA[GTValues.LV])
        .duration(160)

    gtr.chemical_reactor("gtocore:perfluorobenzene")
        .notConsumable("gtceu:rhenium_dust")
        .itemInputs("12x gtceu:potassium_fluoride_dust")
        .inputFluids("gtceu:benzene 1000", "gtceu:chlorine 6000")
        .itemOutputs("12x gtceu:rock_salt_dust")
        .outputFluids("gtceu:perfluorobenzene 1000", "gtceu:hydrogen 6000")
        .EUt(GTValues.VA[GTValues.MV])
        .duration(185)

    gtr.chemical_reactor("gtocore:potassium_fluoride_dust")
        .itemInputs("gtceu:potassium_dust")
        .inputFluids("gtceu:fluorine 1000")
        .itemOutputs("2x gtceu:potassium_fluoride_dust")
        .EUt(GTValues.VA[GTValues.LV])
        .duration(200)

    gtr.large_chemical_reactor("gtocore:fluorocarborane_dust")
        .itemInputs("50x gtceu:cesium_carborane_dust", "10x gtceu:silver_nitrate_dust", "2x gtceu:iodine_dust")
        .inputFluids("gtceu:trimethylsilane 1000", "gtceu:hydrochloric_acid 1000", "gtceu:fluorine 44000")
        .itemOutputs("50x gtceu:fluorocarborane_dust", "10x gtceu:caesium_nitrate_dust", "4x gtceu:silver_iodide_dust")
        .outputFluids("gtceu:hydrofluoric_acid 22000", "gtceu:trimethylchlorosilane 1000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(320)

    gtr.chemical_reactor("gtocore:trimethylchlorosilane")
        .inputFluids("gtceu:methane 1000", "gtceu:dimethyldichlorosilane 1000")
        .outputFluids("gtceu:trimethylchlorosilane 1000", "gtceu:hydrogen 2000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(110)

    gtr.chemical_reactor("gtocore:trimethylsilane")
        .itemInputs("2x gtceu:sodium_hydride_dust")
        .inputFluids("gtceu:trimethylchlorosilane 1000")
        .itemOutputs("2x gtceu:salt_dust")
        .outputFluids("gtceu:trimethylsilane 1000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(190)

    gtr.chemical_reactor("gtocore:sodium_hydride_dust")
        .itemInputs("gtceu:sodium_dust")
        .inputFluids("gtceu:hydrogen 1000")
        .itemOutputs("2x gtceu:sodium_hydride_dust")
        .EUt(GTValues.VA[GTValues.LV])
        .duration(140)

    gtr.chemical_reactor("gtocore:silver_nitrate_dust_chemical_compound")
        .itemInputs("3x gtceu:silver_oxide_dust")
        .inputFluids("gtceu:nitric_acid 2000")
        .itemOutputs("10x gtceu:silver_nitrate_dust")
        .outputFluids("minecraft:water 1000")
        .EUt(125)
        .duration(150)

    gtr.large_chemical_reactor("gtocore:cesium_carborane_dust")
        .notConsumableFluid("gtceu:tetrahydrofuran 1000")
        .itemInputs("38x gtceu:cesium_carborane_precursor_dust", "2x gtceu:sodium_hydride_dust")
        .inputFluids("gtceu:borane_dimethyl_sulfide 1000")
        .itemOutputs("25x gtceu:cesium_carborane_dust", "2x gtceu:salt_dust")
        .outputFluids("gtceu:trimethylamine 1000", "gtceu:hydrogen_sulfide 1000", "gtceu:methane 2000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(260)

    gtr.chemical_reactor("gtocore:borane_dimethyl_sulfide")
        .inputFluids("gtceu:diborane 1000", "gtceu:dimethyl_sulfide 2000")
        .outputFluids("gtceu:borane_dimethyl_sulfide 2000")
        .EUt(125)
        .duration(165)

    gtr.chemical_reactor("gtocore:tetrahydrofuran")
        .inputFluids("gtceu:hydrogen 4000", "gtceu:formaldehyde 2000", "gtceu:acetylene 1000")
        .outputFluids("gtceu:tetrahydrofuran 1000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(75)

    gtr.large_chemical_reactor("gtocore:cesium_carborane_precursor_dust")
        .notConsumableFluid("gtceu:sulfuric_acid 1000")
        .itemInputs("24x gtceu:decaborane_dust", "3x gtceu:caesium_hydroxide_dust")
        .inputFluids("gtceu:methanol 3000", "gtceu:hydrochloric_acid 2000", "gtceu:sodium_cyanide 1000")
        .itemOutputs("38x gtceu:cesium_carborane_precursor_dust", "2x gtceu:salt_dust")
        .outputFluids("minecraft:water 4000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(240)

    gtr.chemical_reactor("gtocore:diborane")
        .itemInputs("18x gtceu:lithium_aluminium_hydride_dust")
        .inputFluids("gtceu:boron_fluoride 4000")
        .itemOutputs("18x gtceu:lithium_aluminium_fluoride_dust")
        .outputFluids("gtceu:diborane 2000")
        .EUt(30)
        .duration(80)

    gtr.large_chemical_reactor("gtocore:decaborane_dust")
        .itemInputs("51x gtceu:sodium_borohydride_dust")
        .inputFluids("gtceu:boron_trifluoride_acetate 10000", "gtceu:hydrogen_peroxide 2000", "gtceu:hydrofluoric_acid 1000")
        .itemOutputs("24x gtceu:decaborane_dust", "2x gtceu:sodium_fluoride_dust", "45x gtceu:sodium_tetrafluoroborate_dust")
        .outputFluids("minecraft:water 1000", "gtceu:hydrogen 20000", "gtceu:diethyl_ether 10000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(380)

    gtr.chemical_reactor("gtocore:lithium_aluminium_hydride_dust")
        .itemInputs("6x gtceu:sodium_aluminium_hydride_dust", "2x gtceu:lithium_chloride_dust")
        .inputFluids("minecraft:water 1000")
        .itemOutputs("6x gtceu:lithium_aluminium_hydride_dust")
        .outputFluids("gtceu:salt_water 1000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(320)

    gtr.chemical_reactor("gtocore:sodium_borohydride_dust")
        .notConsumableFluid("gtceu:sulfuric_acid 1000")
        .itemInputs("8x gtceu:sodium_hydride_dust")
        .inputFluids("gtceu:ethanol 3000", "gtceu:boric_acide 1000")
        .itemOutputs("6x gtceu:sodium_borohydride_dust", "27x gtceu:sodium_ethylate_dust")
        .outputFluids("minecraft:water 3000")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(120)

    gtr.chemical_reactor("gtocore:sodium_tetrafluoroborate_dust")
        .circuit(2)
        .itemInputs("6x gtceu:sodium_tetrafluoroborate_dust")
        .itemOutputs("2x gtceu:sodium_fluoride_dust")
        .outputFluids("gtceu:boron_fluoride 1000")
        .EUt(125)
        .duration(120)

    gtr.chemical_reactor("gtocore:lithium_chloride_dust")
        .circuit(1)
        .itemInputs("gtceu:lithium_dust")
        .inputFluids("gtceu:chlorine 1000")
        .itemOutputs("2x gtceu:lithium_chloride_dust")
        .EUt(GTValues.VA[GTValues.MV])
        .duration(125)

    gtr.chemical_reactor("gtocore:aluminium_trifluoride_dust_a")
        .itemInputs("6x gtceu:sodium_fluoride_dust", "4x gtceu:aluminium_trifluoride_dust")
        .outputFluids("gtceu:sodium_hexafluoroaluminate 1000")
        .EUt(GTValues.VA[GTValues.MV])
        .duration(200)

    gtr.chemical_reactor("gtocore:aluminium_trifluoride_dust_b")
        .itemInputs("8x gtceu:aluminium_trifluoride_dust")
        .inputFluids("minecraft:water 3000")
        .itemOutputs("5x gtceu:alumina_dust")
        .outputFluids("gtceu:hydrofluoric_acid 6000")
        .EUt(GTValues.VA[GTValues.MV])
        .duration(140)

    gtr.chemical_reactor("gtocore:aluminium_hydride_dust")
        .itemInputs("gtceu:aluminium_dust")
        .inputFluids("gtceu:hydrogen 3000")
        .itemOutputs("4x gtceu:aluminium_hydride_dust")
        .EUt(GTValues.VA[GTValues.LV])
        .duration(80)
})
