ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.cutter("gtocore:optical_slice")
        .itemInputs("gtocore:optical_wafer")
        .itemOutputs("16x gtocore:optical_slice")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(560)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:exotic_chip")
        .itemInputs("gtocore:exotic_wafer")
        .itemOutputs("4x gtocore:exotic_chip")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:photocoated_hassium_wafer")
        .itemInputs("gtocore:photocoated_hassium_boule")
        .itemOutputs("4x gtocore:photocoated_hassium_wafer")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(280)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:bioware_chip")
        .itemInputs("gtocore:bioware_boule")
        .itemOutputs("16x gtocore:bioware_chip", "8x gtocore:biological_cells")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(600)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)

    gtr.cutter("gtocore:taranium_wafer")
        .itemInputs("gtocore:taranium_boule")
        .itemOutputs("64x gtocore:taranium_wafer", "64x gtocore:taranium_wafer")
        .EUt(122880)
        .duration(3200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:rutherfordium_neutronium_wafer")
        .itemInputs("gtocore:rutherfordium_neutronium_boule")
        .itemOutputs("64x gtocore:rutherfordium_neutronium_wafer", "32x gtocore:rutherfordium_neutronium_wafer")
        .EUt(30720)
        .duration(3200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:nm_chip")
        .itemInputs("gtocore:nm_wafer")
        .itemOutputs("4x gtocore:nm_chip")
        .EUt(30720)
        .duration(1800)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:pm_chip")
        .itemInputs("gtocore:pm_wafer")
        .itemOutputs("4x gtocore:pm_chip")
        .EUt(122880)
        .duration(1800)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:fm_chip")
        .itemInputs("gtocore:fm_wafer")
        .itemOutputs("2x gtocore:fm_chip")
        .EUt(524288)
        .duration(2700)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:optical_ram_chip")
        .itemInputs("gtocore:optical_ram_wafer")
        .itemOutputs("32x gtocore:optical_ram_chip")
        .EUt(122880)
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:exotic_ram_chip")
        .itemInputs("gtocore:exotic_ram_wafer")
        .itemOutputs("32x gtocore:exotic_ram_chip")
        .EUt(524288)
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:cosmic_ram_chip")
        .itemInputs("gtocore:cosmic_ram_wafer")
        .itemOutputs("32x gtocore:cosmic_ram_chip")
        .EUt(524288 * 4)
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:supracausal_ram_chip")
        .itemInputs("gtocore:supracausal_ram_wafer")
        .itemOutputs("4x gtocore:supracausal_ram_chip")
        .EUt(524288 * 16)
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtocore:cosmic_soc")
        .itemInputs("gtocore:cosmic_soc_wafer")
        .itemOutputs("8x gtocore:cosmic_soc")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)
})