ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.distillation_tower("gtocore:naquadah_fuel")
        .inputFluids("gtceu:fluorine_cracked_aquadah 1000")
        .outputFluids("gtceu:naquadah_fuel 800", "gtceu:nitric_acid 200", "gtceu:enriched_naquadah_waste 100", "gtceu:ammonia 200", "gtceu:fluorine 200")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(600)

    gtr.distillation_tower("gtocore:enriched_naquadah_fuel")
        .inputFluids("gtceu:radon_cracked_enriched_aquadah 1000")
        .outputFluids("gtceu:enriched_naquadah_fuel 800", "gtceu:naquadria_waste 100", "gtceu:radon 200", "gtceu:fluorine 200")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(600)

    gtr.distillation_tower("gtocore:diphenylmethane_diisocyanate_dust")
        .inputFluids("gtceu:diphenylmethanediisocyanatemixture 1000")
        .itemOutputs("29x gtceu:diphenylmethane_diisocyanate_dust")
        .outputFluids("gtceu:hydrochloric_acid 5000")
        .EUt(1920)
        .duration(700)

    gtr.distillation_tower("gtocore:rawradox")
        .inputFluids("gtceu:rawradox 5000")
        .outputFluids("gtceu:oil_heavy 600", "gtceu:oil 300", "gtceu:creosote 1000", "minecraft:water 1400", "gtceu:bacteria 50", "gtceu:fermented_biomass 50", "gtceu:superheavyradox 100", "gtceu:heavyradox 100", "gtceu:dilutedxenoxene 100", "gtceu:lightradox 100", "gtceu:superlightradox 100")
        .itemOutputs("5x gtceu:ash_dust")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(800)

    gtr.distillation_tower("gtocore:radox_gas")
        .inputFluids("gtceu:crackedradox 1000")
        .outputFluids("gtceu:radox_gas 100", "gtceu:lightradox 200")
        .EUt(GTValues.VA[GTValues.UV])
        .itemOutputs("gtceu:ash_dust")
        .duration(600)

    gtr.distillation_tower("gtocore:dilutedxenoxene")
        .inputFluids("gtceu:dilutedxenoxene 1000")
        .outputFluids("gtceu:xenoxene 250", "gtceu:lightradox 300")
        .itemOutputs("gtceu:ash_dust")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(200)

    gtr.distillation_tower("gtocore:turpentine")
        .inputFluids("gtceu:steam_cracked_turpentine 1000")
        .outputFluids("gtceu:turpentine 1000", "gtceu:naphtha 900")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(400)

    gtr.distillery("gtocore:fluoro_benzene")
        .inputFluids("gtceu:benzenediazonium_tetrafluoroborate 1000")
        .outputFluids("gtceu:fluoro_benzene 1000")
        .EUt(122880)
        .duration(100)

    gtr.distillery("gtocore:enriched_potassium_iodide_slurry")
        .inputFluids("gtceu:kelp_slurry 1000")
        .outputFluids("gtceu:enriched_potassium_iodide_slurry 100")
        .EUt(30)
        .duration(200)

    gtr.distillery("gtocore:enriched_dragon_breath")
        .inputFluids("gtceu:dragon_breath 10")
        .outputFluids("gtceu:enriched_dragon_breath 5")
        .EUt(120)
        .duration(100)
        .cleanroom(GTOCleanroomType.LAW_CLEANROOM)

    gtr.distillery("gtocore:cyclopentadiene")
        .inputFluids("gtceu:severely_steam_cracked_naphtha 1000")
        .outputFluids("gtceu:cyclopentadiene 150")
        .circuit(12)
        .EUt(30)
        .duration(240)

    gtr.distillery("gtocore:kerosene")
        .itemInputs("gtceu:coke_dust")
        .inputFluids("gtceu:coal_tar 200")
        .outputFluids("gtceu:kerosene 100")
        .itemOutputs("gtceu:dark_ash_dust")
        .EUt(120)
        .duration(30)

    gtr.distillery("gtocore:rp_1")
        .circuit(1)
        .inputFluids("gtceu:kerosene 50")
        .outputFluids("gtceu:rp_1 25")
        .EUt(120)
        .duration(16)
})