ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.dimensionally_transcendent_plasma_forge("gtocore:hypercube")
        .itemInputs("12x gtceu:cosmic_neutronium_rod", "24x gtceu:celestial_tungsten_rod")
        .inputFluids("gtceu:exciteddtec 1000")
        .itemOutputs("gtocore:hypercube")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(2400)
        .blastFurnaceTemp(30000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:chaos_plasma")
        .itemInputs("gtocore:chaos_shard")
        .inputFluids("gtceu:dimensionallytranscendentresplendentcatalyst 1000", "gtceu:cosmic_mesh_plasma 1000")
        .outputFluids("gtceu:chaos_plasma 1000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(1600)
        .blastFurnaceTemp(32000)

    gtr.dimensionally_transcendent_plasma_forge("avaritia:infinity_catalyst")
        .itemInputs("64x gtocore:contained_exotic_matter", "64x gtocore:essentia_matter")
        .inputFluids("gtceu:infinity 1000", "gtceu:high_energy_quark_gluon_plasma 100000")
        .itemOutputs("avaritia:infinity_catalyst", "64x gtocore:time_dilation_containment_unit")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(4800)
        .blastFurnaceTemp(32000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:transcendent_metal")
        .notConsumable("gtocore:spacetime_catalyst")
        .itemInputs("gtocore:hypercube")
        .inputFluids("gtceu:spacetime 100", "gtceu:tennessine 144")
        .outputFluids("gtceu:transcendent_metal 144", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(3200)
        .blastFurnaceTemp(36000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:cosmic_neutron_plasma_cell")
        .notConsumable("avaritia:infinity_catalyst")
        .itemInputs("5x gtocore:extremely_durable_plasma_cell")
        .inputFluids("gtceu:uu_matter 1000000", "gtceu:dense_neutron_plasma 1000")
        .itemOutputs("5x gtocore:cosmic_neutron_plasma_cell")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)
        .blastFurnaceTemp(28000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:crystal_matrix_plasma")
        .notConsumable("avaritia:infinity_catalyst")
        .itemInputs("avaritia:crystal_matrix")
        .inputFluids("gtceu:uu_matter 1000000", "gtceu:free_proton_gas 20000")
        .outputFluids("gtceu:crystal_matrix_plasma 10000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)
        .blastFurnaceTemp(28000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:infinity")
        .notConsumable("gtocore:spacetime_catalyst")
        .inputFluids("gtceu:crystal_matrix_plasma 10000", "gtceu:cosmic_neutronium 5000")
        .outputFluids("gtceu:infinity 1000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(4 * GTValues.VA[GTValues.MAX])
        .duration(1600)
        .blastFurnaceTemp(32000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:dimensionallytranscendentresidue")
        .inputFluids("gtceu:dimensionallytranscendentcrudecatalyst 100", "gtceu:raw_star_matter_plasma 100")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(400)
        .blastFurnaceTemp(36000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:spacetime_ingot")
        .notConsumable("64x kubejs:ingot_field_shape")
        .notConsumable("64x gtocore:spacetimebendingcore")
        .inputFluids("gtceu:spacetime 1000", "gtceu:raw_star_matter_plasma 1000")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .itemOutputs("8x gtceu:spacetime_ingot")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(6400)
        .blastFurnaceTemp(62000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:spacetime")
        .notConsumable("gtocore:spacetime_catalyst")
        .inputFluids("gtceu:infinity 100", "gtceu:hypogen 100")
        .outputFluids("gtceu:spacetime 200", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(4 * GTValues.VA[GTValues.MAX])
        .duration(1600)
        .blastFurnaceTemp(36000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:magneto_hydro_dynamically_con_strained_star_matter")
        .notConsumable("gtocore:eternity_catalyst")
        .itemInputs("gtceu:eternity_nanites")
        .chancedOutput("gtceu:contaminable_eternity_nanites", 5000, 0)
        .inputFluids("gtceu:raw_star_matter_plasma 100000", "gtceu:exciteddtsc 100000")
        .outputFluids("gtceu:magneto_hydro_dynamically_con_strained_star_matter 100000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(1024 * GTValues.VA[GTValues.MAX])
        .duration(6400)
        .blastFurnaceTemp(81000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:dense_neutron_plasma")
        .notConsumable("avaritia:infinity_catalyst")
        .itemInputs("gtocore:neutron_plasma_containment_cell")
        .inputFluids("gtceu:heavy_quark_degenerate_matter_plasma 10000", "gtceu:periodicium 1000")
        .outputFluids("gtceu:dense_neutron_plasma 10000", "gtceu:dimensionallytranscendentresidue 100")
        .itemOutputs("gtocore:plasma_containment_cell")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)
        .blastFurnaceTemp(26000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:eternity")
        .notConsumable("gtocore:eternity_catalyst")
        .itemInputs("avaritia:eternal_singularity")
        .inputFluids("gtceu:primordialmatter 1000", "gtceu:raw_star_matter_plasma 9000")
        .outputFluids("gtceu:eternity 10000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(16 * GTValues.VA[GTValues.MAX])
        .duration(4800)
        .blastFurnaceTemp(56000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:rhugnor")
        .notConsumable("avaritia:infinity_catalyst")
        .itemInputs("64x gtceu:energy_crystal")
        .inputFluids("gtceu:infinity 10000", "gtceu:quantum 10000")
        .outputFluids("gtceu:rhugnor 10000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(4 * GTValues.VA[GTValues.MAX])
        .duration(3600)
        .blastFurnaceTemp(36000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:hypogen")
        .notConsumable("avaritia:infinity_catalyst")
        .itemInputs("gtceu:quantum_chromo_dynamically_confined_matter_block")
        .inputFluids("gtceu:rhugnor 10000", "gtceu:dragon_blood 10000")
        .outputFluids("gtceu:hypogen 10000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(1200)
        .blastFurnaceTemp(26000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:infinity_glass")
        .itemInputs("gtocore:black_body_naquadria_supersolid", "2x gtceu:infinity_dust")
        .inputFluids("gtceu:dimensionallytranscendentexoticcatalyst 1000", "gtceu:woods_glass 9216")
        .itemOutputs("gtocore:infinity_glass")
        .EUt(4096 * GTValues.VA[GTValues.MAX])
        .duration(1600)
        .blastFurnaceTemp(88000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:create_casing")
        .itemInputs("gtceu:eternity_frame", "gtocore:command_block_core")
        .inputFluids("gtceu:exciteddtsc 1000", "gtceu:primordialmatter 1000")
        .itemOutputs("gtocore:create_casing")
        .EUt(16384 * GTValues.VA[GTValues.MAX])
        .duration(3200)
        .blastFurnaceTemp(96000)

    gtr.dimensionally_transcendent_plasma_forge("gtocore:hypercube_1")
        .itemInputs("16x gtceu:transcendent_metal_rod", "gtocore:quantum_anomaly")
        .inputFluids("gtceu:exciteddtec 1000", "gtceu:spatialfluid 1000")
        .itemOutputs("64x gtocore:hypercube")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .EUt(16 * GTValues.VA[GTValues.MAX])
        .duration(6400)
        .blastFurnaceTemp(62000)

    gtr.stellar_forge("gtocore:eternity_dust")
        .itemInputs("4x gtocore:quantum_chromodynamic_charge", "avaritia:eternal_singularity")
        .inputFluids("gtceu:primordialmatter 1000", "gtceu:dimensionallytranscendentresidue 1000")
        .itemOutputs("gtceu:eternity_dust")
        .outputFluids("gtceu:temporalfluid 1000")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)

    gtr.stellar_forge("gtocore:temporalfluid")
        .itemInputs("4x gtocore:quantum_chromodynamic_charge", "gtocore:hypercube")
        .inputFluids("gtceu:spacetime 1000", "gtceu:dimensionallytranscendentresidue 100")
        .outputFluids("gtceu:temporalfluid 500", "gtceu:spatialfluid 500")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)

    gtr.stellar_forge("gtocore:cosmic_mesh_plasma")
        .itemInputs("gtocore:quantum_chromodynamic_charge", "gtocore:highly_dense_polymer_plate")
        .outputFluids("gtceu:cosmic_mesh_plasma 1000")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)


    gtr.stellar_forge("gtocore:exciteddtec")
        .itemInputs("gtocore:quantum_chromodynamic_charge", "enderio:prescient_powder")
        .inputFluids("gtceu:dimensionallytranscendentexoticcatalyst 10000")
        .outputFluids("gtceu:exciteddtec 10000")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)

    gtr.stellar_forge("gtocore:neutron_plasma_containment_cell")
        .inputFluids("gtceu:neutronium 1000", "gtceu:heavy_lepton_mixture 1000")
        .itemInputs("gtocore:naquadria_charge", "gtocore:plasma_containment_cell")
        .itemOutputs("gtocore:neutron_plasma_containment_cell")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 1)

    gtr.stellar_forge("gtocore:free_proton_gas")
        .itemInputs("gtocore:naquadria_charge", "gtocore:contained_high_density_protonic_matter")
        .outputFluids("gtceu:free_proton_gas 10000")
        .itemOutputs("gtocore:time_dilation_containment_unit")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 1)

    gtr.stellar_forge("gtocore:enderium_plasma")
        .inputFluids("gtceu:ender_eye 2304", "gtceu:lead 2304", "gtceu:bismuth 2304", "gtceu:platinum 1152", "gtceu:liquid_ender_air 100000")
        .itemInputs("gtocore:naquadria_charge", "enderio:ender_crystal_powder")
        .outputFluids("gtceu:enderium_plasma 2304")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 1)

    gtr.stellar_forge("gtocore:adamantium_plasma")
        .inputFluids("gtceu:orichalcum 576", "gtceu:tin 1024", "gtceu:antimony 864", "gtceu:iron 1152", "gtceu:mercury 1000")
        .itemInputs("gtocore:naquadria_charge", "24x gtceu:bloodstone_dust")
        .outputFluids("gtceu:adamantium_plasma 2304")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 1)

    gtr.stellar_forge("gtocore:degenerate_rhenium_plasma")
        .itemInputs("gtocore:naquadria_charge", "5x gtceu:double_rhenium_plate")
        .outputFluids("gtceu:degenerate_rhenium_plasma 10000")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 1)

    gtr.stellar_forge("gtocore:infuscolium_plasma")
        .inputFluids("gtceu:adamantine 2304", "gtceu:mana 10000")
        .itemInputs("gtocore:naquadria_charge", "16x minecraft:end_crystal", "16x minecraft:popped_chorus_fruit")
        .outputFluids("gtceu:infuscolium_plasma 2304")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 1)

    gtr.stellar_forge("gtocore:legendarium_plasma")
        .inputFluids("gtceu:naquadriatictaranium 576", "gtceu:trinium 288", "gtceu:duranium 288", "gtceu:tritanium 288", "gtceu:orichalcum 288", "gtceu:mithril 288", "gtceu:adamantium 288", "gtceu:adamantine 288", "gtceu:vibranium 288")
        .itemInputs("gtocore:leptonic_charge", "gtocore:neutron_plasma_containment_cell")
        .outputFluids("gtceu:legendarium_plasma 2304")
        .itemOutputs("gtocore:plasma_containment_cell")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 2)

    gtr.stellar_forge("gtocore:astral_titanium_plasma")
        .itemInputs("gtocore:naquadria_charge")
        .inputFluids("gtceu:force 576", "gtceu:titanium 576", "gtceu:cobalt 288", "gtceu:copper 288", "gtceu:tritium 1000")
        .outputFluids("gtceu:astral_titanium_plasma 1000")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 1)

    gtr.stellar_forge("gtocore:celestial_tungsten_plasma")
        .itemInputs("gtocore:naquadria_charge")
        .inputFluids("gtceu:tartarite 576", "gtceu:tungsten 576", "gtceu:americium 288", "gtceu:titan_precision_steel 144", "gtceu:astral_titanium 144", "gtceu:xenon 1000")
        .outputFluids("gtceu:celestial_tungsten_plasma 1000")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 1)

    gtr.stellar_forge("gtocore:quark_gluon_plasma")
        .itemInputs("gtocore:leptonic_charge", "10x gtceu:degenerate_rhenium_dust")
        .outputFluids("gtceu:quark_gluon_plasma 10000")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 2)

    gtr.stellar_forge("gtocore:heavy_quark_degenerate_matter_plasma")
        .inputFluids("gtceu:heavy_quark_enriched_mixture 1152", "gtceu:flerovium 144", "gtceu:oganesson 144", "gtceu:hassium 144", "gtceu:deuterium 1000")
        .itemInputs("gtocore:leptonic_charge")
        .outputFluids("gtceu:heavy_quark_degenerate_matter_plasma 1152")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 2)

    gtr.stellar_forge("gtocore:contained_high_density_protonic_matter")
        .itemInputs("gtocore:leptonic_charge", "gtocore:time_dilation_containment_unit", "gtocore:charged_triplet_neutronium_sphere")
        .itemOutputs("gtocore:contained_high_density_protonic_matter")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 2)

    gtr.stellar_forge("gtocore:crystal_matrix_plasma")
        .itemInputs("gtocore:leptonic_charge", "avaritia:crystal_matrix", "16x gtocore:corporeal_matter")
        .inputFluids("gtceu:free_proton_gas 20000")
        .outputFluids("gtceu:crystal_matrix_plasma 1000")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 2)

    gtr.stellar_forge("gtocore:starmetal_plasma")
        .itemInputs("gtocore:leptonic_charge", "10x gtocore:resonating_gem")
        .inputFluids("gtceu:free_proton_gas 1000", "gtceu:free_electron_gas 1000")
        .outputFluids("gtceu:starmetal_plasma 1000")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 2)

    gtr.stellar_forge("gtocore:high_energy_quark_gluon_plasma")
        .itemInputs("gtocore:quantum_chromodynamic_charge", "10x gtceu:double_heavy_quark_degenerate_matter_plate", "enderio:pulsating_powder")
        .outputFluids("gtceu:high_energy_quark_gluon_plasma 2000")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 2)

    gtr.stellar_forge("gtocore:quantum_chromo_dynamically_confined_matter_plasma")
        .itemInputs("gtocore:quantum_chromodynamic_charge", "20x gtocore:quantumchromodynamic_protective_plating")
        .outputFluids("gtceu:quantum_chromo_dynamically_confined_matter_plasma 2000")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)

    gtr.stellar_forge("gtocore:dense_neutron_plasma")
        .inputFluids("gtceu:periodicium 2736", "gtceu:gluons 6000", "gtceu:heavy_lepton_mixture 6000")
        .itemInputs("gtocore:quantum_chromodynamic_charge", "5x gtceu:neutronium_block", "5x gtceu:heavy_quark_degenerate_matter_block")
        .outputFluids("gtceu:dense_neutron_plasma 6000")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)

    gtr.stellar_forge("gtocore:extremely_durable_plasma_cell")
        .itemInputs("gtocore:quantum_chromodynamic_charge", "2x gtocore:dense_neutron_plasma_cell")
        .itemOutputs("gtocore:cosmic_neutron_plasma_cell", "gtocore:extremely_durable_plasma_cell")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)

    gtr.stellar_forge("gtocore:infinity_ingot")
        .inputFluids("gtceu:crystal_matrix 2000", "gtceu:cosmic_neutronium 1000")
        .itemInputs("gtocore:quantum_chromodynamic_charge", "enderio:vibrant_powder")
        .itemOutputs("gtceu:hot_infinity_ingot")
        .outputFluids("gtceu:infinity 10")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)

    gtr.stellar_forge("gtocore:contained_reissner_nordstrom_singularity")
        .itemInputs("gtocore:naquadria_charge", "64x gtocore:time_dilation_containment_unit", "64x gtocore:charged_triplet_neutronium_sphere")
        .itemOutputs("64x gtocore:contained_reissner_nordstrom_singularity")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 1)

    gtr.stellar_forge("gtocore:contained_kerr_newmann_singularity")
        .itemInputs("gtocore:leptonic_charge", "64x gtocore:contained_reissner_nordstrom_singularity")
        .itemOutputs("gtocore:contained_kerr_newmann_singularity", "63x gtocore:time_dilation_containment_unit")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 2)

    gtr.stellar_forge("gtocore:contained_exotic_matter")
        .itemInputs("gtocore:leptonic_charge", "gtocore:contained_high_density_protonic_matter", "9x gtceu:tiny_degenerate_rhenium_dust")
        .itemOutputs("gtocore:contained_exotic_matter")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 2)

    gtr.stellar_forge("gtocore:recursively_folded_negative_space")
        .itemInputs("gtocore:quantum_chromodynamic_charge", "2x gtocore:macrowormhole_generator", "2x gtocore:temporal_matter")
        .itemOutputs("gtocore:recursively_folded_negative_space")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)

    gtr.stellar_forge("gtocore:eigenfolded_kerr_manifold")
        .itemInputs("gtocore:quantum_chromodynamic_charge", "gtocore:stabilized_wormhole_generator", "gtocore:recursively_folded_negative_space")
        .itemOutputs("gtocore:eigenfolded_kerr_manifold")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)

    gtr.stellar_forge("gtocore:ctc_computational_unit")
        .itemInputs("gtocore:quantum_chromodynamic_charge", "gtocore:eigenfolded_kerr_manifold", "gtocore:ctc_computational_unit_container")
        .itemOutputs("gtocore:ctc_computational_unit")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)

    gtr.stellar_forge("gtocore:dragon_heart")
        .itemInputs("gtocore:naquadria_charge", "64x minecraft:dragon_egg", "gtceu:double_awakened_draconium_plate")
        .itemOutputs("gtocore:dragon_heart")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 1)

    gtr.stellar_forge("gtocore:chaos_shard")
        .itemInputs("gtocore:quantum_chromodynamic_charge", "gtocore:infused_obsidian", "minecraft:bedrock")
        .inputFluids("gtceu:radox 1000")
        .itemOutputs("gtocore:chaos_shard")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 3)

    gtr.stellar_forge("gtocore:actinium_superhydride_plasma")
        .itemInputs("gtocore:naquadria_charge", "36x gtceu:atinium_hydride_dust")
        .inputFluids("gtceu:hydrogen 81000")
        .outputFluids("gtceu:actinium_superhydride_plasma 36000")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData(GTOValue.STELLAR_CONTAINMENT_TIER, 1)

    gtr.ultimate_material_forge("gtocore:proto_matter")
        .itemInputs("gtocore:triplet_neutronium_sphere")
        .inputFluids("gtceu:uu_matter 1000")
        .itemOutputs("gtocore:proto_matter")
        .chancedOutput("gtceu:neutronium_ingot", 6000, 0)
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(1600)

    gtr.ultimate_material_forge("gtocore:pellet_antimatter")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:antihydrogen 10")
        .itemInputs("64x ae2:matter_ball", "gtceu:neutronium_nugget")
        .itemOutputs("gtocore:pellet_antimatter")
        .chancedOutput("gtocore:void_matter", 100, 0)
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(2000)

    gtr.ultimate_material_forge("gtocore:corporeal_matter")
        .itemInputs("gtocore:proto_matter", "minecraft:iron_block")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:nihonium 100")
        .itemOutputs("gtocore:corporeal_matter")
        .chancedOutput("gtceu:heavy_quark_degenerate_matter_nugget", 500, 0)
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(800)

    gtr.ultimate_material_forge("gtocore:kinetic_matter")
        .itemInputs("gtocore:corporeal_matter", "gtceu:tritanium_block")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:naquadria 1000")
        .itemOutputs("gtocore:kinetic_matter")
        .chancedOutput("gtocore:amorphous_matter", 200, 0)
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(600)

    gtr.ultimate_material_forge("gtocore:amorphous_matter")
        .itemInputs("gtocore:corporeal_matter", "gtceu:carbon_nanotubes_block")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:legendarium 1000")
        .itemOutputs("gtocore:amorphous_matter")
        .chancedOutput("gtocore:essentia_matter", 100, 0)
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(800)

    gtr.ultimate_material_forge("gtocore:essentia_matter")
        .itemInputs("gtocore:amorphous_matter", "gtceu:heavy_quark_degenerate_matter_block")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:quantum_chromo_dynamically_confined_matter 1000")
        .itemOutputs("gtocore:essentia_matter")
        .chancedOutput("gtocore:dark_matter", 100, 0)
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(1200)

    gtr.ultimate_material_forge("gtocore:omni_matter")
        .itemInputs("gtocore:essentia_matter", "gtocore:kinetic_matter")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:dense_neutron_plasma 1000")
        .itemOutputs("gtocore:omni_matter")
        .chancedOutput("gtceu:tiny_cosmic_neutronium_dust", 1000, 0)
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)

    gtr.ultimate_material_forge("gtocore:void_matter")
        .itemInputs("gtocore:omni_matter", "gtocore:pellet_antimatter")
        .inputFluids("gtceu:uu_matter 2000", "gtceu:gluons 1000")
        .itemOutputs("gtocore:void_matter")
        .chancedOutput("gtocore:corporeal_matter", 2000, 0)
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(400)

    gtr.ultimate_material_forge("gtocore:temporal_matter")
        .notConsumable("gtocore:quantum_anomaly")
        .itemInputs("gtocore:kinetic_matter")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:awakened_draconium_plasma 1000")
        .itemOutputs("gtocore:temporal_matter")
        .chancedOutput("gtocore:omni_matter", 500, 0)
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(600)

    gtr.ultimate_material_forge("gtocore:dark_matter")
        .itemInputs("gtocore:temporal_matter", "gtocore:void_matter")
        .inputFluids("gtceu:uu_matter 3000", "gtceu:dimensionallytranscendentcrudecatalyst 1000")
        .itemOutputs("gtocore:dark_matter")
        .chancedOutput("gtocore:kinetic_matter", 1000, 0)
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(1200)

    gtr.nano_forge("gtocore:carbon_nanites")
        .notConsumable("gtceu:lime_glass_lens")
        .itemInputs("64x gtceu:carbon_block", "64x gtceu:soc")
        .itemOutputs("64x gtceu:carbon_nanites")
        .inputFluids("gtceu:soldering_alloy 20000", "gtceu:lubricant 20000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:glowstone_nanites")
        .notConsumable("gtceu:orange_glass_lens")
        .itemInputs("64x minecraft:glowstone", "64x gtceu:advanced_soc")
        .itemOutputs("64x gtceu:glowstone_nanites")
        .inputFluids("gtceu:uu_amplifier 10000", "gtceu:soldering_alloy 20000", "gtceu:lubricant 20000")
        .duration(16000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:copper_nanites")
        .notConsumable("gtceu:brown_glass_lens")
        .itemInputs("8x minecraft:copper_block", "8x gtceu:soc")
        .itemOutputs("gtceu:copper_nanites")
        .inputFluids("gtceu:naquadah 2000", "gtceu:soldering_alloy 10000", "gtceu:bismuth 10000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:iron_nanites")
        .notConsumable("gtceu:gray_glass_lens")
        .itemInputs("8x minecraft:iron_block", "8x gtceu:soc")
        .itemOutputs("gtceu:iron_nanites")
        .inputFluids("gtceu:naquadah 2000", "gtceu:soldering_alloy 10000", "gtceu:bismuth 10000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:gold_nanites")
        .notConsumable("gtceu:yellow_glass_lens")
        .itemInputs("8x minecraft:gold_block", "16x gtceu:soc")
        .itemOutputs("gtceu:gold_nanites")
        .inputFluids("gtceu:enriched_naquadah 2000", "gtceu:soldering_alloy 20000", "gtceu:bismuth 20000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:silver_nanites")
        .notConsumable("gtceu:light_gray_glass_lens")
        .itemInputs("8x gtceu:silver_block", "16x gtceu:soc")
        .itemOutputs("gtceu:silver_nanites")
        .inputFluids("gtceu:enriched_naquadah 2000", "gtceu:soldering_alloy 20000", "gtceu:bismuth 20000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:iridium_nanites")
        .notConsumable("gtceu:glass_lens")
        .itemInputs("8x gtceu:iridium_block", "32x gtceu:soc")
        .itemOutputs("gtceu:iridium_nanites")
        .inputFluids("gtceu:naquadria 2000", "gtceu:hafnium 8000", "gtceu:soldering_alloy 20000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:osmium_nanites")
        .notConsumable("gtceu:diamond_lens")
        .itemInputs("8x gtceu:osmium_block", "32x gtceu:soc")
        .itemOutputs("gtceu:osmium_nanites")
        .inputFluids("gtceu:naquadria 2000", "gtceu:hafnium 8000", "gtceu:soldering_alloy 20000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:rhenium_nanites")
        .notConsumable("gtceu:cyan_glass_lens")
        .itemInputs("8x gtceu:rhenium_block", "64x gtceu:soc")
        .itemOutputs("gtceu:rhenium_nanites")
        .inputFluids("gtceu:naquadria 2000", "gtceu:uu_amplifier 2000", "gtceu:soldering_alloy 20000")
        .duration(8000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:naquadah_nanites")
        .notConsumable("gtceu:emerald_lens")
        .itemInputs("8x gtceu:naquadah_block", "16x gtceu:advanced_soc")
        .itemOutputs("gtceu:naquadah_nanites")
        .inputFluids("gtceu:naquadria 8000", "gtceu:uu_amplifier 2000", "gtceu:mutated_living_solder 20000")
        .duration(16000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:neutronium_nanites")
        .notConsumable("gtceu:nether_star_lens")
        .itemInputs("8x gtceu:neutronium_block", "64x gtceu:soc", "32x gtceu:advanced_soc")
        .itemOutputs("gtceu:neutronium_nanites")
        .inputFluids("gtceu:neutronium 4000", "gtceu:uu_amplifier 2000", "gtceu:mutated_living_solder 20000")
        .duration(32000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:orichalcum_nanites")
        .notConsumable("gtceu:magenta_glass_lens")
        .itemInputs("8x gtceu:orichalcum_block", "64x gtceu:advanced_soc", "64x gtceu:advanced_soc")
        .itemOutputs("gtceu:orichalcum_nanites")
        .inputFluids("gtceu:neutronium 8000", "gtceu:uu_amplifier 4000", "gtceu:mutated_living_solder 40000")
        .duration(32000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtocore:enderium_nanites")
        .notConsumable("gtceu:green_glass_lens")
        .itemInputs("8x gtceu:enderium_block", "64x gtceu:advanced_soc", "64x gtceu:advanced_soc")
        .itemOutputs("gtceu:enderium_nanites")
        .inputFluids("gtceu:neutronium 8000", "gtceu:uu_amplifier 4000", "gtceu:mutated_living_solder 40000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtocore:infuscolium_nanites")
        .notConsumable("gtceu:pink_glass_lens")
        .itemInputs("8x gtceu:infuscolium_block", "64x gtceu:advanced_soc", "32x gtceu:highly_advanced_soc")
        .itemOutputs("gtceu:infuscolium_nanites")
        .inputFluids("gtceu:neutronium 8000", "gtceu:uu_amplifier 4000", "gtceu:mutated_living_solder 40000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtocore:uruium_nanites")
        .notConsumable("gtceu:light_blue_glass_lens")
        .itemInputs("8x gtceu:uruium_block", "64x gtceu:advanced_soc", "64x gtceu:highly_advanced_soc")
        .itemOutputs("gtceu:uruium_nanites")
        .inputFluids("gtceu:uu_matter 20000", "gtceu:mutated_living_solder 40000", "gtceu:super_mutated_living_solder 40000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtocore:vibranium_nanites")
        .notConsumable("gtceu:light_blue_glass_lens")
        .itemInputs("8x gtceu:vibranium_block", "64x gtceu:highly_advanced_soc", "64x gtceu:highly_advanced_soc")
        .itemOutputs("gtceu:vibranium_nanites")
        .inputFluids("gtceu:uu_matter 20000", "gtceu:mutated_living_solder 40000", "gtceu:super_mutated_living_solder 40000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtocore:starmetal_nanites")
        .notConsumable("gtceu:red_glass_lens")
        .itemInputs("8x gtceu:starmetal_block", "64x gtceu:highly_advanced_soc", "64x gtceu:highly_advanced_soc", "64x gtceu:exquisite_glass_gem", "64x gtceu:exquisite_amethyst_gem")
        .itemOutputs("gtceu:starmetal_nanites")
        .inputFluids("gtceu:uu_matter 40000", "gtceu:mutated_living_solder 80000", "gtceu:super_mutated_living_solder 80000")
        .duration(8000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtocore:draconium_nanites")
        .notConsumable("gtceu:purple_glass_lens")
        .itemInputs("8x gtceu:draconium_block", "32x gtceu:highly_advanced_soc_wafer", "32x gtocore:optical_ram_wafer", "32x gtocore:optical_soc", "8x gtocore:exotic_processing_core")
        .itemOutputs("gtceu:draconium_nanites")
        .inputFluids("gtceu:uu_matter 40000", "gtceu:mutated_living_solder 80000", "gtceu:super_mutated_living_solder 80000")
        .duration(16000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtocore:cosmic_neutronium_nanites")
        .notConsumable("gtceu:black_glass_lens")
        .itemInputs("8x gtceu:cosmic_neutronium_block", "32x gtocore:optical_soc", "32x gtocore:exotic_wafer", "16x gtocore:cosmic_ram_wafer", "8x gtocore:cosmic_processing_unit_core")
        .itemOutputs("gtceu:cosmic_neutronium_nanites")
        .inputFluids("gtceu:uu_matter 40000", "gtceu:crystal_matrix 40000", "gtceu:liquid_cosmic_mesh 40000")
        .duration(8000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)

    gtr.nano_forge("gtocore:white_dwarf_mtter_nanites")
        .notConsumable("gtceu:ruby_lens")
        .itemInputs("8x gtceu:white_dwarf_mtter_block", "8x gtocore:cosmic_processing_unit_core")
        .itemOutputs("gtceu:white_dwarf_mtter_nanites")
        .inputFluids("gtceu:uu_matter 40000", "gtceu:neutronium 40000", "gtceu:cosmic_element 40000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)

    gtr.nano_forge("gtocore:black_dwarf_mtter_nanites")
        .notConsumable("gtceu:ruby_lens")
        .itemInputs("8x gtceu:black_dwarf_mtter_block", "8x gtocore:cosmic_processing_unit_core")
        .itemOutputs("gtceu:black_dwarf_mtter_nanites")
        .inputFluids("gtceu:uu_matter 40000", "gtceu:neutronium 40000", "gtceu:cosmic_element 40000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)

    gtr.nano_forge("gtocore:spacetime_nanites")
        .notConsumable("gtceu:sapphire_lens")
        .notConsumable("gtocore:quantum_anomaly")
        .itemInputs("8x gtceu:spacetime_block", "4x gtocore:eigenfolded_kerr_manifold", "16x gtocore:supracausal_ram_wafer", "8x gtocore:supracausal_processing_core")
        .itemOutputs("gtceu:spacetime_nanites")
        .inputFluids("gtceu:uu_matter 80000", "gtceu:infinity 40000", "gtceu:temporalfluid 40000")
        .duration(8000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)

    gtr.nano_forge("gtocore:transcendent_metal_nanites")
        .notConsumable("kubejs:non_linear_optical_lens")
        .notConsumable("gtocore:hypercube")
        .itemInputs("gtceu:rhenium_nanites", "8x gtceu:transcendent_metal_block", "8x gtocore:recursively_folded_negative_space", "#gtceu:circuits/max")
        .itemOutputs("gtceu:transcendent_metal_nanites")
        .inputFluids("gtceu:uu_matter 80000", "gtceu:raw_star_matter_plasma 40000", "gtceu:spatialfluid 20000")
        .duration(16000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)

    gtr.nano_forge("gtocore:eternity_nanites")
        .notConsumable("gtceu:blue_glass_lens")
        .notConsumable("gtocore:quantum_anomaly")
        .notConsumable("gtocore:eternity_catalyst")
        .itemInputs("gtceu:neutronium_nanites", "8x gtceu:eternity_block", "8x gtocore:ctc_computational_unit")
        .itemOutputs("gtceu:eternity_nanites")
        .inputFluids("gtceu:spatialfluid 80000", "gtceu:exciteddtsc 80000", "gtceu:primordialmatter 80000")
        .duration(64000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)
})