ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.fuel_refining("gtocore:cetane_boosted_diesel")
        .itemInputs("16x gtceu:carbon_dust")
        .inputFluids("gtceu:hydrogen 10000", "gtceu:oxygen 5000", "gtceu:light_fuel 10000", "gtceu:heavy_fuel 2000", "gtceu:nitration_mixture 4000")
        .outputFluids("gtceu:cetane_boosted_diesel 18000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(400)
        .blastFurnaceTemp(4800)

    gtr.fuel_refining("gtocore:cetane_boosted_diesel_b")
        .itemInputs("12x gtceu:carbon_dust")
        .inputFluids("gtceu:hydrogen 10000", "gtceu:oxygen 5000", "gtceu:bio_diesel 16000", "gtceu:nitration_mixture 4000")
        .outputFluids("gtceu:cetane_boosted_diesel 14000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(600)
        .blastFurnaceTemp(3600)

    gtr.fuel_refining("gtocore:high_octane_gasoline")
        .itemInputs("44x gtceu:carbon_dust")
        .inputFluids("gtceu:oxygen 12000", "gtceu:nitrogen 8000", "gtceu:naphtha 16000", "gtceu:refinery_gas 2000", "gtceu:toluene 4000", "gtceu:octane 3000")
        .outputFluids("gtceu:high_octane_gasoline 50000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(1200)
        .blastFurnaceTemp(6800)

    gtr.fuel_refining("gtocore:rocket_fuel")
        .circuit(1)
        .itemInputs("8x gtceu:carbon_dust")
        .inputFluids("gtceu:hydrogen 32000", "gtceu:oxygen 14000", "gtceu:nitrogen 12000", "gtceu:chlorine 10000")
        .outputFluids("gtceu:rocket_fuel 36000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(1600)
        .blastFurnaceTemp(5200)

    gtr.fuel_refining("gtocore:rocket_fuel_rp_1")
        .circuit(2)
        .itemInputs("64x gtceu:carbon_dust")
        .inputFluids("gtceu:coal_gas 80000", "gtceu:oxygen 10000")
        .outputFluids("gtceu:rocket_fuel_rp_1 4000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(1200)
        .blastFurnaceTemp(6300)

    gtr.fuel_refining("gtocore:dense_hydrazine_fuel_mixture")
        .circuit(3)
        .itemInputs("32x gtceu:carbon_dust")
        .inputFluids("gtceu:hydrogen 12000", "gtceu:oxygen 8000", "gtceu:nitrogen 10000", "gtceu:hydrogen_peroxide 4000")
        .outputFluids("gtceu:dense_hydrazine_fuel_mixture 8000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(800)
        .blastFurnaceTemp(7400)

    gtr.fuel_refining("gtocore:rocket_fuel_cn3h7o3")
        .circuit(4)
        .itemInputs("12x gtceu:carbon_dust")
        .inputFluids("gtceu:hydrogen 14000", "gtceu:nitrogen 6000", "gtceu:nitric_acid 3000", "gtceu:hydrogen_peroxide 2000")
        .outputFluids("gtceu:rocket_fuel_cn3h7o3 4000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(1200)
        .blastFurnaceTemp(8200)

    gtr.fuel_refining("gtocore:rocket_fuel_h8n4c2o4")
        .circuit(2)
        .itemInputs("18x gtceu:carbon_dust")
        .inputFluids("gtceu:hydrogen 30000", "gtceu:nitrogen 18000", "gtceu:oxygen 24000", "gtceu:chlorine 10000")
        .outputFluids("gtceu:rocket_fuel_h8n4c2o4 12000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(2000)
        .blastFurnaceTemp(9000)

    gtr.fuel_refining("ad_astra:cryo_fuel")
        .itemInputs("8x ad_astra:ice_shard", "60x gtceu:carbon_dust")
        .inputFluids("gtceu:hydrogen 42000", "gtceu:oxygen 20000", "gtceu:nitrogen 8000", "gtceu:heavy_fuel 1000", "gtceu:light_fuel 4000")
        .outputFluids("ad_astra:cryo_fuel 8000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(6400)
        .blastFurnaceTemp(11800)

    gtr.fuel_refining("gtocore:stellar_energy_rocket_fuel")
        .itemInputs("64x minecraft:fire_charge", "8x gtceu:hmxexplosive_dust", "4x gtceu:enriched_naquadah_dust")
        .inputFluids("gtceu:hydrogen_peroxide 8000", "gtceu:rocket_fuel_cn3h7o3 8000", "gtceu:dense_hydrazine_fuel_mixture 12000", "gtceu:rocket_fuel_rp_1 4000", "gtceu:nitration_mixture 4000", "gtceu:benzene 4000")
        .outputFluids("gtceu:stellar_energy_rocket_fuel 40000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(7200)
        .blastFurnaceTemp(14400)

    gtr.fuel_refining("gtocore:hyper_fuel_1")
        .inputFluids("gtceu:naquadria_solution 1000", "gtceu:naquadah_fuel 1000", "gtceu:enriched_naquadah_fuel 1000", "gtceu:thorium 2304")
        .outputFluids("gtceu:hyper_fuel_1 3000")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(400)
        .blastFurnaceTemp(12400)

    gtr.atomic_energy_excitation("gtocore:naquadah_fuel")
        .notConsumable("gtceu:orichalcum_nanites")
        .itemInputs("16x gtceu:naquadah_dust")
        .inputFluids("gtceu:hydrogen 30000", "gtceu:nitrogen 15000", "gtceu:fluorine 8000", "gtceu:nitric_acid 8000")
        .outputFluids("gtceu:naquadah_fuel 20000")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(4000)
        .blastFurnaceTemp(12000)

    gtr.atomic_energy_excitation("gtocore:enriched_naquadah_fuel")
        .notConsumable("gtceu:vibranium_nanites")
        .notConsumableFluid("gtceu:caesium_fluoride 1000")
        .itemInputs("16x gtceu:enriched_naquadah_dust", "4x gtceu:antimony_dust")
        .inputFluids("gtceu:hydrogen 48000", "gtceu:nitrogen 30000", "gtceu:fluorine 12000", "gtceu:xenon 8000", "gtceu:radon 6000")
        .outputFluids("gtceu:enriched_naquadah_fuel 20000")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(4000)
        .blastFurnaceTemp(12500)

    gtr.atomic_energy_excitation("gtocore:hyper_fuel_1")
        .itemInputs("14x gtceu:naquadria_dust", "20x gtceu:enriched_naquadah_dust", "40x gtceu:naquadah_dust")
        .inputFluids("gtceu:hydrogen 100000", "gtceu:nitrogen 76000", "gtceu:fluorine 10000", "gtceu:radon 2000", "gtceu:xenon 4000", "gtceu:thorium 4608")
        .outputFluids("gtceu:hyper_fuel_1 24000")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(3800)
        .blastFurnaceTemp(13200)

    gtr.atomic_energy_excitation("gtocore:hyper_fuel_2")
        .itemInputs("4x gtceu:dubnium_dust", "6x gtceu:fermium_dust")
        .inputFluids("gtceu:hyper_fuel_1 6000", "gtceu:radon 40000", "gtceu:xenon 32000", "gtceu:thorium 3456", "gtceu:naquadria 864", "gtceu:uranium_235 2304")
        .outputFluids("gtceu:hyper_fuel_2 9600", "gtceu:hyper_fuel_1 500")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(4000)
        .blastFurnaceTemp(14000)

    gtr.atomic_energy_excitation("gtocore:hyper_fuel_3")
        .itemInputs("6x gtceu:lawrencium_dust", "8x gtceu:adamantine_dust")
        .inputFluids("gtceu:hyper_fuel_2 6000", "gtceu:naquadria 864", "gtceu:thorium 1728", "gtceu:fermium 5184", "gtceu:uranium_235 2304", "gtceu:plutonium_241 4608")
        .outputFluids("gtceu:hyper_fuel_3 12000", "gtceu:hyper_fuel_2 750")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(4000)
        .blastFurnaceTemp(15200)

    gtr.atomic_energy_excitation("gtocore:hyper_fuel_4")
        .itemInputs("8x gtceu:neutronium_dust", "12x gtceu:taranium_dust")
        .inputFluids("gtceu:hyper_fuel_3 6000", "gtceu:nobelium 8000", "gtceu:thorium 1728", "gtceu:fermium 2340", "gtceu:uranium_235 2304", "gtceu:plutonium_241 5184")
        .outputFluids("gtceu:hyper_fuel_4 16000", "gtceu:hyper_fuel_3 1000")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(4200)
        .blastFurnaceTemp(18000)

    gtr.atomic_energy_excitation("gtocore:concentration_mixing_hyper_fuel_1")
        .notConsumable("gtceu:white_dwarf_mtter_nanites")
        .itemInputs("4x gtocore:resonating_gem", "16x gtceu:hassium_dust")
        .inputFluids("gtceu:hyper_fuel_4 8000", "gtceu:helium_plasma 6000", "gtceu:nickel_plasma 6000", "gtceu:oganesson 1152", "gtceu:naquadriatictaranium 2304", "gtceu:plutonium_241 864")
        .outputFluids("gtceu:concentration_mixing_hyper_fuel_1 12000", "gtceu:hyper_fuel_4 1500")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(1200)
        .blastFurnaceTemp(18800)

    gtr.atomic_energy_excitation("gtocore:concentration_mixing_hyper_fuel_2")
        .notConsumable("gtceu:black_dwarf_mtter_nanites")
        .itemInputs("16x gtceu:draconium_dust", "18x gtceu:starmetal_dust")
        .inputFluids("gtceu:concentration_mixing_hyper_fuel_1 6000", "gtceu:cosmic_element 60000", "gtceu:oxygen_plasma 6000", "gtceu:argon_plasma 6000", "gtceu:iron_plasma 6000", "gtceu:nitrogen_plasma 6000")
        .outputFluids("gtceu:concentration_mixing_hyper_fuel_2 12000", "gtceu:concentration_mixing_hyper_fuel_1 2000")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(2400)
        .blastFurnaceTemp(21000)

    gtr.mixer("gtocore:concentration_mixing_hyper_fuel_1")
        .itemInputs("gtceu:hassium_dust", "gtceu:oganesson_dust")
        .inputFluids("gtceu:hyper_fuel_4 1000", "gtceu:dimensionallytranscendentcrudecatalyst 1000")
        .outputFluids("gtceu:concentration_mixing_hyper_fuel_1 1000")
        .EUt(GTValues.V[GTValues.UXV])
        .duration(800)

    gtr.fuel_refining("gtocore:concentration_mixing_hyper_fuel_2")
        .itemInputs("gtceu:starmetal_dust", "gtceu:draconium_dust")
        .inputFluids("gtceu:concentration_mixing_hyper_fuel_1 1000", "gtceu:dimensionallytranscendentprosaiccatalyst 1000")
        .outputFluids("gtceu:concentration_mixing_hyper_fuel_2 1000")
        .EUt(GTValues.V[GTValues.OpV])
        .duration(800)
        .blastFurnaceTemp(18800)

    gtr.rocket_engine("gtceu:rocket_engine_fuel_7")
        .inputFluids("ad_astra:cryo_fuel 10")
        .duration(120)
        .EUt(-2048)

    gtr.annihilate_generator("gtocore:neutronium_antimatter_fuel_rod")
        .itemInputs("gtocore:neutronium_antimatter_fuel_rod")
        .chancedOutput("gtocore:annihilation_constrainer", 9000, 0)
        .duration(200)
        .EUt(-GTValues.V[GTValues.MAX] * 256)

    gtr.annihilate_generator("gtocore:draconium_antimatter_fuel_rod")
        .itemInputs("gtocore:draconium_antimatter_fuel_rod")
        .chancedOutput("gtocore:annihilation_constrainer", 8000, 0)
        .duration(200)
        .EUt(-GTValues.V[GTValues.MAX] * 4096)

    gtr.annihilate_generator("gtocore:cosmic_neutronium_antimatter_fuel_rod")
        .itemInputs("gtocore:cosmic_neutronium_antimatter_fuel_rod")
        .chancedOutput("gtocore:annihilation_constrainer", 7000, 0)
        .duration(200)
        .EUt(-GTValues.V[GTValues.MAX] * 65536)

    gtr.annihilate_generator("gtocore:infinity_antimatter_fuel_rod")
        .itemInputs("gtocore:infinity_antimatter_fuel_rod")
        .chancedOutput("gtocore:annihilation_constrainer", 6000, 0)
        .duration(200)
        .EUt(-GTValues.V[GTValues.MAX] * 1048576)
})