ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.electric_blast_furnace("gtocore:shining_obsidian")
        .itemInputs("minecraft:obsidian", "gtceu:vibrant_alloy_dust")
        .inputFluids("gtceu:glowstone 576")
        .itemOutputs("gtocore:shining_obsidian")
        .EUt(480)
        .duration(600)
        .blastFurnaceTemp(2600)

    gtr.electric_blast_furnace("gtocore:bedrock_smoke")
        .itemInputs("gtceu:bedrock_dust")
        .inputFluids("gtceu:xenon 100")
        .outputFluids("gtceu:bedrock_smoke 1000")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(400)
        .blastFurnaceTemp(16200)

    gtr.electric_blast_furnace("gtocore:hot_draconium_ingot_1")
        .itemInputs("gtceu:draconium_dust")
        .inputFluids("gtceu:cetane_boosted_diesel 2000")
        .itemOutputs("gtceu:hot_draconium_ingot")
        .EUt(GTValues.VA[GTValues.UXV])
        .blastFurnaceTemp(21600)
        .duration(800)

    gtr.electric_blast_furnace("gtocore:hot_draconium_ingot_2")
        .itemInputs("gtceu:draconium_dust")
        .inputFluids("gtceu:gasoline 1000")
        .itemOutputs("gtceu:hot_draconium_ingot")
        .EUt(GTValues.VA[GTValues.UXV])
        .blastFurnaceTemp(21600)
        .duration(400)

    gtr.electric_blast_furnace("gtocore:hot_draconium_ingot_3")
        .itemInputs("gtceu:draconium_dust")
        .inputFluids("gtceu:high_octane_gasoline 500")
        .itemOutputs("gtceu:hot_draconium_ingot")
        .EUt(GTValues.VA[GTValues.UXV])
        .blastFurnaceTemp(21600)
        .duration(200)

    gtr.electric_blast_furnace("gtocore:rutherfordium_neutronium_boule")
        .itemInputs("gtceu:neutronium_boule", "4x gtceu:rutherfordium_dust")
        .inputFluids("gtceu:radon 8000")
        .itemOutputs("gtocore:rutherfordium_neutronium_boule")
        .EUt(30720)
        .duration(21000)
        .blastFurnaceTemp(8100)

    gtr.electric_blast_furnace("gtocore:lepton_trap_crystal")
        .itemInputs("gtceu:meitnerium_dust", "gtceu:molybdenum_dust", "gtceu:rhenium_dust")
        .inputFluids("gtceu:naquadah_alloy 288")
        .itemOutputs("gtocore:lepton_trap_crystal")
        .EUt(3450000)
        .duration(340)
        .blastFurnaceTemp(10900)

    gtr.electric_blast_furnace("gtocore:taranium_boulea")
        .itemInputs("64x gtceu:silicon_block", "8x gtceu:taranium_ingot", "4x gtceu:gallium_arsenide_dust")
        .inputFluids("gtceu:radon 16000")
        .itemOutputs("gtocore:taranium_boule")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(24000)
        .blastFurnaceTemp(10500)

    gtr.electric_blast_furnace("gtocore:giga_chad")
        .itemInputs("64x gtceu:uiv_field_generator", "64x gtceu:uxv_field_generator", "64x gtceu:opv_field_generator")
        .inputFluids("gtceu:exciteddtec 10000000")
        .itemOutputs("gtocore:giga_chad")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(4000)
        .blastFurnaceTemp(36000)

    gtr.liquefaction_furnace("gtocore:antimatter")
        .itemInputs("gtocore:pellet_antimatter")
        .outputFluids("gtceu:antimatter 1000")
        .duration(2000)
        .EUt(480)
        .blastFurnaceTemp(19999)

    gtr.liquefaction_furnace("gtocore:gelid_cryotheum")
        .itemInputs("gtocore:dust_cryotheum")
        .outputFluids("gtocore:gelid_cryotheum 144")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(80)
        .blastFurnaceTemp(300)

    const rare_earth_oxides = ["lanthanum",
        "praseodymium",
        "neodymium",
        "promethium",
        "cerium",
        "scandium",
        "europium",
        "gadolinium",
        "samarium",
        "terbium",
        "dysprosium",
        "holmium",
        "erbium",
        "thulium",
        "ytterbium",
        "lutetium",
        "yttrium"]

    rare_earth_oxides.forEach((element) => {
        gtr.reaction_furnace("gtocore:" + element + "_dust")
            .itemInputs("10x gtceu:" + element + "_oxide_dust", "3x gtceu:carbon_dust")
            .itemOutputs("4x gtceu:" + element + "_dust")
            .outputFluids("gtceu:carbon_dioxide 3000")
            .EUt(480)
            .duration(200)
            .blastFurnaceTemp(2500)
    })

    gtr.reaction_furnace("gtocore:thallium_thulium_doped_caesium_iodide_dust")
        .itemInputs("gtceu:caesium_iodide_dust", "gtceu:small_thulium_dust", "gtceu:small_thallium_dust")
        .itemOutputs("gtceu:thallium_thulium_doped_caesium_iodide_dust")
        .EUt(120)
        .duration(260)
        .blastFurnaceTemp(2853)

    gtr.reaction_furnace("gtocore:calcium_carbide_dust")
        .itemInputs("2x gtceu:carbon_dust", "2x gtceu:quicklime_dust")
        .itemOutputs("gtceu:calcium_carbide_dust")
        .outputFluids("gtceu:oxygen 1000")
        .EUt(120)
        .duration(100)
        .blastFurnaceTemp(800)

    gtr.reaction_furnace("gtocore:germanium_dust")
        .itemInputs("3x gtceu:germanium_dioxide_dust")
        .inputFluids("gtceu:hydrogen 4000")
        .itemOutputs("gtceu:germanium_dust")
        .EUt(120)
        .duration(200)
        .blastFurnaceTemp(680)

    gtr.reaction_furnace("gtocore:molybdenum_flue")
        .itemInputs("4x gtceu:molybdenum_concentrate_dust")
        .inputFluids("gtceu:oxygen 7250")
        .itemOutputs("4x gtceu:molybdenum_trioxide_dust")
        .outputFluids("gtceu:molybdenum_flue 3000")
        .EUt(120)
        .duration(340)
        .blastFurnaceTemp(2400)

    gtr.reaction_furnace("gtocore:zylon_dust")
        .itemInputs("gtceu:pre_zylon_dust")
        .outputFluids("gtceu:propane 2000")
        .itemOutputs("gtceu:zylon_dust")
        .EUt(120)
        .duration(16000)
        .blastFurnaceTemp(10000)

    gtr.reaction_furnace("gtocore:hot_titanium_50_ingot")
        .itemInputs("2x gtceu:magnesium_dust")
        .inputFluids("gtceu:titanium_50_tetrachloride 1000")
        .itemOutputs("gtceu:hot_titanium_50_ingot", "6x gtceu:magnesium_chloride_dust")
        .EUt(480)
        .duration(600)
        .blastFurnaceTemp(2142)

    gtr.reaction_furnace("gtocore:zeolite_sieving_pellets_dust")
        .itemInputs("gtceu:silica_alumina_gel_dust", "gtceu:zeolite_dust")
        .itemOutputs("gtceu:zeolite_sieving_pellets_dust")
        .blastFurnaceTemp(4500)
        .EUt(120)
        .duration(400)

    gtr.reaction_furnace("gtocore:cubic_zirconia_dust")
        .itemInputs("gtceu:zirconium_dust")
        .itemOutputs("3x gtceu:cubic_zirconia_dust")
        .inputFluids("gtceu:oxygen 2000")
        .EUt(480)
        .duration(360)
        .blastFurnaceTemp(2600)

    gtr.reaction_furnace("gtocore:strontium_europium_aluminate_dust")
        .itemInputs("2x gtceu:aluminium_dust", "gtceu:europium_dust", "gtceu:strontium_dust")
        .inputFluids("gtceu:oxygen 4000")
        .itemOutputs("8x gtceu:strontium_europium_aluminate_dust")
        .EUt(120)
        .duration(340)
        .blastFurnaceTemp(1200)

    gtr.reaction_furnace("gtocore:francium_caesium_cadmium_bromide_dust")
        .itemInputs("2x gtceu:cadmium_dust", "gtceu:francium_dust", "gtceu:caesium_dust")
        .inputFluids("gtceu:bromine 6000")
        .itemOutputs("10x gtceu:francium_caesium_cadmium_bromide_dust")
        .EUt(120)
        .duration(250)
        .blastFurnaceTemp(2200)

    gtr.reaction_furnace("gtocore:infused_obsidian")
        .itemInputs("gtocore:ender_obsidian", "gtocore:draconium_dust")
        .itemOutputs("gtocore:infused_obsidian")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(200)
        .blastFurnaceTemp(11200)

    gtr.reaction_furnace("gtocore:fissioned_uranium_235_dust")
        .itemInputs("gtceu:uranium_235_dust", "gtceu:tiny_neutronium_dust")
        .itemOutputs("gtceu:fissioned_uranium_235_dust")
        .EUt(1920)
        .duration(800)
        .blastFurnaceTemp(3860)

    gtr.reaction_furnace("gtocore:bisethylenedithiotetraselenafulvalene_perrhenate_dust")
        .itemInputs("26x gtceu:bisethylenedithiotetraselenafulvalene_dust")
        .inputFluids("gtceu:ammonium_perrhenate 1000")
        .outputFluids("gtceu:ammonia 1000")
        .itemOutputs("31x gtceu:bisethylenedithiotetraselenafulvalene_perrhenate_dust")
        .EUt(120)
        .duration(9840)
        .blastFurnaceTemp(5000)

    gtr.reaction_furnace("gtocore:bisethylenedithiotetraselenafulvalene_dust")
        .itemInputs("28x gtceu:lithiumthiinediselenide_dust", "gtceu:cyclopentadienyl_titanium_trichloride_dust")
        .inputFluids("gtceu:tetrafluoroethylene 1000")
        .itemOutputs("8x gtceu:lithium_fluoride_dust", "26x gtceu:bisethylenedithiotetraselenafulvalene_dust")
        .EUt(120)
        .duration(7680)
        .blastFurnaceTemp(4600)

    gtr.reaction_furnace("gtocore:sodium_thiosulfate_dust")
        .itemInputs("18x gtceu:sodium_hydroxide_dust", "4x gtceu:sulfur_dust")
        .itemOutputs("7x gtceu:sodium_thiosulfate_dust", "6x gtceu:sodium_sulfide_dust")
        .outputFluids("gtceu:steam 3000")
        .EUt(120)
        .duration(210)
        .blastFurnaceTemp(4500)

    gtr.reaction_furnace("gtocore:boron_carbide_dust")
        .itemInputs("3x gtceu:carbon_dust", "4x gtceu:boron_dust")
        .itemOutputs("7x gtceu:boron_carbide_dust")
        .EUt(120)
        .duration(550)
        .blastFurnaceTemp(4000)

    gtr.reaction_furnace("gtocore:borocarbide_dust")
        .itemInputs("15x gtceu:boron_francium_carbide_dust", "14x gtceu:mixed_astatide_salts_dust")
        .itemOutputs("29x gtceu:borocarbide_dust")
        .EUt(120)
        .duration(15000)
        .blastFurnaceTemp(11300)

    gtr.reaction_furnace("gtocore:dust_cryotheum")
        .itemInputs("gtocore:dust_blizz", "gtceu:enderium_dust")
        .itemOutputs("2x gtocore:dust_cryotheum")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(160)
        .blastFurnaceTemp(8300)

    gtr.reaction_furnace("gtocore:hassium_chloride_dust")
        .itemInputs("gtceu:hassium_dust")
        .inputFluids("gtceu:chlorine 4000")
        .itemOutputs("5x gtceu:hassium_chloride_dust")
        .EUt(120)
        .duration(930)
        .blastFurnaceTemp(12000)

    gtr.reaction_furnace("gtocore:rhenium_chloride_dust")
        .itemInputs("gtceu:rhenium_dust")
        .inputFluids("gtceu:chlorine 5000")
        .itemOutputs("6x gtceu:rhenium_chloride_dust")
        .EUt(120)
        .duration(930)
        .blastFurnaceTemp(12500)

    gtr.reaction_furnace("gtocore:atinium_hydride_dust")
        .itemInputs("13x gtceu:actinium_oxalate_dust", "6x gtceu:sodium_hydride_dust", "gtceu:sodium_dust")
        .inputFluids("gtceu:carbon_tetrachloride 3000")
        .itemOutputs("4x gtceu:atinium_hydride_dust", "8x gtceu:salt_dust")
        .outputFluids("gtceu:carbon_dioxide 5000")
        .EUt(122880)
        .duration(400)
        .blastFurnaceTemp(10700)

    gtr.reaction_furnace("gtocore:dragon_strength_tritanium_casing")
        .itemInputs("16x gtocore:extreme_strength_tritanium_casing", "16x gtocore:draconium_block_charged")
        .itemOutputs("gtocore:dragon_strength_tritanium_casing")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2000)
        .blastFurnaceTemp(8000)

    gtr.reaction_furnace("gtocore:blaze_blast_furnace_casing")
        .itemInputs("gtceu:high_temperature_smelting_casing", "32x gtceu:tin_foil")
        .inputFluids("gtceu:blaze 1440", "gtceu:gallium_arsenide 576", "gtceu:vanadium_gallium 288")
        .itemOutputs("gtocore:blaze_blast_furnace_casing")
        .EUt(1920)
        .duration(900)
        .blastFurnaceTemp(4500)

    gtr.reaction_furnace("gtocore:aerographene")
        .itemInputs("gtceu:dry_graphene_gel_dust")
        .inputFluids("gtceu:supercritical_carbon_dioxide 1000")
        .itemOutputs("gtocore:aerographene")
        .EUt(120)
        .duration(400)
        .blastFurnaceTemp(5000)

    gtr.reaction_furnace("gtocore:iridium_dioxide_dust")
        .itemInputs("6x gtceu:iridium_metal_residue_dust", "5x gtceu:sodium_chlorate_dust")
        .inputFluids("gtceu:hydrogen 1000")
        .itemOutputs("3x gtceu:iridium_dioxide_dust", "2x gtceu:salt_dust")
        .chancedOutput("gtceu:platinum_sludge_residue_dust", 8000, 0)
        .outputFluids("gtceu:diluted_hydrochloric_acid 1000")
        .EUt(120)
        .duration(200)
        .blastFurnaceTemp(790)

    gtr.reaction_furnace("gtocore:hafnium_dust")
        .itemInputs("5x gtceu:hafnium_chloride_dust", "2x gtceu:magnesium_dust")
        .itemOutputs("gtceu:hafnium_dust", "6x gtceu:magnesium_chloride_dust")
        .EUt(120)
        .duration(300)
        .blastFurnaceTemp(3400)

    gtr.reaction_furnace("gtocore:tellurium_oxide_dust")
        .itemInputs("gtceu:tellurium_dust")
        .inputFluids("gtceu:oxygen 2000")
        .itemOutputs("3x gtceu:tellurium_oxide_dust")
        .EUt(128)
        .duration(100)
        .blastFurnaceTemp(1760)

    gtr.reaction_furnace("gtocore:cadmium_tungstate_dust")
        .itemInputs("4x gtceu:tungsten_trioxide_dust", "2x gtceu:cadmium_sulfide_dust")
        .inputFluids("gtceu:oxygen 3000")
        .itemOutputs("6x gtceu:cadmium_tungstate_dust")
        .outputFluids("gtceu:sulfur_dioxide 1000")
        .EUt(120)
        .duration(320)
        .blastFurnaceTemp(2800)

    gtr.reaction_furnace("gtocore:cadmium_sulfide_dust")
        .itemInputs("gtceu:cadmium_dust", "gtceu:sulfur_dust")
        .itemOutputs("2x gtceu:cadmium_sulfide_dust")
        .EUt(30)
        .duration(400)
        .blastFurnaceTemp(1200)

    gtr.reaction_furnace("gtocore:bismuth_germanate_dust")
        .itemInputs("3x gtceu:germanium_dioxide_dust")
        .inputFluids("gtceu:bismuth_nitrate_solution 4000")
        .itemOutputs("33x gtceu:bismuth_germanate_dust")
        .outputFluids("gtceu:nitrogen_dioxide 12000")
        .EUt(5000000)
        .duration(80)
        .blastFurnaceTemp(7600)

    gtr.reaction_furnace("gtocore:trinium_compound_dust")
        .itemInputs("40x gtceu:crystalline_nitric_acid_dust", "16x gtceu:trinium_compound_dust", "6x gtceu:sodium_perchlorate_dust")
        .inputFluids("gtceu:sulfur_dioxide 8000")
        .itemOutputs("8x gtceu:astatine_dust", "24x gtceu:selenium_oxide_dust")
        .outputFluids("gtceu:nitrated_triniite_compound_solution 4000")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(265)
        .blastFurnaceTemp(9400)

    gtr.reaction_furnace("gtocore:phosphorus_pentasulfide_dust")
        .itemInputs("10x gtceu:sulfur_dust", "4x gtceu:phosphorus_dust")
        .itemOutputs("14x gtceu:phosphorus_pentasulfide_dust")
        .EUt(GTValues.VA[GTValues.HV])
        .duration(190)
        .blastFurnaceTemp(900)

    gtr.reaction_furnace("gtocore:silver_iodide_dust")
        .itemInputs("4x gtceu:silver_iodide_dust")
        .inputFluids("gtceu:oxygen 1000")
        .itemOutputs("3x gtceu:silver_oxide_dust", "2x gtceu:iodine_dust")
        .EUt(125)
        .duration(210)
        .blastFurnaceTemp(1100)

})