ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    const isa_mill_ores = [
        ["gtceu:milled_almandine", "gtceu:raw_almandine", "#forge:gt_ores/almandine"],
        ["gtceu:milled_chalcopyrite", "gtceu:raw_chalcopyrite", "#forge:gt_ores/chalcopyrite"],
        ["gtceu:milled_grossular", "gtceu:raw_grossular", "#forge:gt_ores/grossular"],
        ["gtceu:milled_monazite", "gtceu:raw_monazite", "#forge:gt_ores/monazite"],
        ["gtceu:milled_nickel", "gtceu:raw_nickel", "#forge:gt_ores/nickel"],
        ["gtceu:milled_pentlandite", "gtceu:raw_pentlandite", "#forge:gt_ores/pentlandite"],
        ["gtceu:milled_platinum", "gtceu:raw_platinum", "#forge:gt_ores/platinum"],
        ["gtceu:milled_pyrope", "gtceu:raw_pyrope", "#forge:gt_ores/pyrope"],
        ["gtceu:milled_redstone", "gtceu:raw_redstone", "#forge:gt_ores/redstone"],
        ["gtceu:milled_spessartine", "gtceu:raw_spessartine", "#forge:gt_ores/spessartine"],
        ["gtceu:milled_sphalerite", "gtceu:raw_sphalerite", "#forge:gt_ores/sphalerite"],
        ["gtceu:milled_enriched_naquadah", "gtceu:raw_enriched_naquadah", "#forge:gt_ores/enriched_naquadah"]]
    isa_mill_ores.forEach((isa_mill_ore) => {
        gtr.isa_mill(isa_mill_ore[0] + "_rgs")
            .circuit(1)
            .itemInputs("16x " + isa_mill_ore[1])
            .inputFluids("gtceu:distilled_water 50")
            .itemOutputs("48x " + isa_mill_ore[0])
            .EUt(GTValues.VA[GTValues.EV])
            .duration(2400)
            .addData("grindball", 1)

        gtr.isa_mill(isa_mill_ore[0] + "_ral")
            .circuit(10)
            .itemInputs("16x " + isa_mill_ore[1])
            .inputFluids("gtceu:distilled_water 50")
            .itemOutputs("36x " + isa_mill_ore[0])
            .EUt(GTValues.VA[GTValues.EV])
            .duration(1200)
            .addData("grindball", 2)

        gtr.isa_mill(isa_mill_ore[0] + "_bgs")
            .circuit(1)
            .itemInputs("16x " + isa_mill_ore[2])
            .inputFluids("gtceu:distilled_water 100")
            .itemOutputs("96x " + isa_mill_ore[0])
            .EUt(GTValues.VA[GTValues.EV])
            .duration(4800)
            .addData("grindball", 1)

        gtr.isa_mill(isa_mill_ore[0] + "_bal")
            .circuit(10)
            .itemInputs("16x " + isa_mill_ore[2])
            .inputFluids("gtceu:distilled_water 100")
            .itemOutputs("72x " + isa_mill_ore[0])
            .EUt(GTValues.VA[GTValues.EV])
            .duration(2400)
            .addData("grindball", 2)
    })

    gtr.flotating_beneficiation("gtocore:almandine_front")
        .itemInputs("32x gtceu:sodium_ethylxanthate_dust", "64x gtceu:milled_almandine")
        .inputFluids("gtceu:turpentine 18000")
        .outputFluids("gtceu:almandine_front 1000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(4800)

    gtr.flotating_beneficiation("gtocore:chalcopyrite_front")
        .itemInputs("32x gtceu:potassium_ethylxanthate_dust", "64x gtceu:milled_chalcopyrite")
        .inputFluids("gtceu:turpentine 12000")
        .outputFluids("gtceu:chalcopyrite_front 1000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(4800)

    gtr.flotating_beneficiation("gtocore:grossular_front")
        .itemInputs("32x gtceu:potassium_ethylxanthate_dust", "64x gtceu:milled_grossular")
        .inputFluids("gtceu:turpentine 28000")
        .outputFluids("gtceu:grossular_front 1000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(4800)

    gtr.flotating_beneficiation("gtocore:monazite_front")
        .itemInputs("32x gtceu:sodium_ethylxanthate_dust", "64x gtceu:milled_monazite")
        .inputFluids("gtceu:turpentine 30000")
        .outputFluids("gtceu:monazite_front 1000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(4800)

    gtr.flotating_beneficiation("gtocore:nickel_front")
        .itemInputs("32x gtceu:potassium_ethylxanthate_dust", "64x gtceu:milled_nickel")
        .inputFluids("gtceu:turpentine 25000")
        .outputFluids("gtceu:nickel_front 1000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(4800)

    gtr.flotating_beneficiation("gtocore:platinum_front")
        .itemInputs("32x gtceu:sodium_ethylxanthate_dust", "64x gtceu:milled_platinum")
        .inputFluids("gtceu:turpentine 35000")
        .outputFluids("gtceu:platinum_front 1000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(4800)

    gtr.flotating_beneficiation("gtocore:pyrope_front")
        .itemInputs("32x gtceu:sodium_ethylxanthate_dust", "64x gtceu:milled_pyrope")
        .inputFluids("gtceu:turpentine 8000")
        .outputFluids("gtceu:pyrope_front 1000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(4800)

    gtr.flotating_beneficiation("gtocore:redstone_front")
        .itemInputs("32x gtceu:sodium_ethylxanthate_dust", "64x gtceu:milled_redstone")
        .inputFluids("gtceu:turpentine 13000")
        .outputFluids("gtceu:redstone_front 1000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(4800)

    gtr.flotating_beneficiation("gtocore:spessartine_front")
        .itemInputs("32x gtceu:potassium_ethylxanthate_dust", "64x gtceu:milled_spessartine")
        .inputFluids("gtceu:turpentine 35000")
        .outputFluids("gtceu:spessartine_front 1000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(4800)

    gtr.flotating_beneficiation("gtocore:sphalerite_front")
        .itemInputs("32x gtceu:sodium_ethylxanthate_dust", "64x gtceu:milled_sphalerite")
        .inputFluids("gtceu:turpentine 14000")
        .outputFluids("gtceu:sphalerite_front 1000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(4800)

    gtr.flotating_beneficiation("gtocore:pentlandite_front")
        .itemInputs("32x gtceu:potassium_ethylxanthate_dust", "64x gtceu:milled_pentlandite")
        .inputFluids("gtceu:turpentine 14000")
        .outputFluids("gtceu:pentlandite_front 1000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(4800)

    gtr.flotating_beneficiation("gtocore:enriched_naquadah_front")
        .itemInputs("64x gtceu:potassium_ethylxanthate_dust", "64x gtceu:milled_enriched_naquadah")
        .inputFluids("gtceu:turpentine 140000")
        .outputFluids("gtceu:enriched_naquadah_front 1000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(9600)

    gtr.vacuum_drying("gtocore:almandine_front_pro")
        .inputFluids("gtceu:almandine_front 4000")
        .itemOutputs("64x gtceu:aluminium_dust", "64x gtceu:aluminium_dust", "64x gtceu:manganese_dust", "24x gtceu:manganese_dust", "24x gtceu:yttrium_dust", "16x gtceu:ytterbium_dust")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(2400)
        .blastFurnaceTemp(5500)

    gtr.vacuum_drying("gtocore:chalcopyrite_front_pro")
        .inputFluids("gtceu:chalcopyrite_front 4000")
        .itemOutputs("64x enderio:powdered_copper", "64x enderio:powdered_copper", "64x enderio:powdered_iron", "48x enderio:powdered_iron", "48x gtceu:cadmium_dust", "32x gtceu:indium_dust")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(2400)
        .blastFurnaceTemp(4500)

    gtr.vacuum_drying("gtocore:grossular_front_pro")
        .inputFluids("gtceu:grossular_front 4000")
        .itemOutputs("64x gtceu:calcium_dust", "64x gtceu:calcium_dust", "64x gtceu:aluminium_dust", "64x gtceu:aluminium_dust", "64x gtceu:tungsten_dust", "16x gtceu:thallium_dust")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(2400)
        .blastFurnaceTemp(5500)

    gtr.vacuum_drying("gtocore:monazite_front_pro")
        .inputFluids("gtceu:monazite_front 4000")
        .itemOutputs("64x gtceu:erbium_dust", "64x gtceu:neodymium_dust", "48x gtceu:thorium_dust", "32x gtceu:lanthanum_dust", "16x gtceu:lutetium_dust", "8x gtceu:europium_dust")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(2400)
        .blastFurnaceTemp(5500)

    gtr.vacuum_drying("gtocore:nickel_front_pro")
        .inputFluids("gtceu:nickel_front 4000")
        .itemOutputs("64x gtceu:nickel_dust", "64x gtceu:nickel_dust", "64x enderio:powdered_cobalt", "64x enderio:powdered_cobalt", "32x enderio:powdered_iron", "32x gtceu:rhodium_dust")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(2400)
        .blastFurnaceTemp(4500)

    gtr.vacuum_drying("gtocore:platinum_front_pro")
        .inputFluids("gtceu:platinum_front 4000")
        .itemOutputs("64x gtceu:platinum_dust", "48x gtceu:nickel_dust", "32x gtceu:iridium_dust", "32x gtceu:osmium_dust", "32x gtceu:palladium_dust", "32x enderio:powdered_cobalt")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(2400)
        .blastFurnaceTemp(5500)

    gtr.vacuum_drying("gtocore:pyrope_front_pro")
        .inputFluids("gtceu:pyrope_front 4000")
        .itemOutputs("64x gtceu:magnesium_dust", "64x gtceu:magnesium_dust", "64x gtceu:aluminium_dust", "64x gtceu:manganese_dust", "64x gtceu:boron_dust", "48x gtceu:silicon_dust")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.EV])
        .duration(2400)
        .blastFurnaceTemp(3500)

    gtr.vacuum_drying("gtocore:redstone_front_pro")
        .inputFluids("gtceu:redstone_front 4000")
        .itemOutputs("64x minecraft:redstone", "64x minecraft:redstone", "64x gtceu:manganese_dust", "64x gtceu:manganese_dust", "32x gtceu:yttrium_dust", "16x gtceu:ytterbium_dust")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.IV])
        .duration(2400)
        .blastFurnaceTemp(4500)

    gtr.vacuum_drying("gtocore:spessartine_front_pro")
        .inputFluids("gtceu:spessartine_front 4000")
        .itemOutputs("64x gtceu:manganese_dust", "64x gtceu:manganese_dust", "64x gtceu:aluminium_dust", "32x gtceu:aluminium_dust", "32x gtceu:palladium_dust", "16x gtceu:strontium_dust")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(2400)
        .blastFurnaceTemp(5500)

    gtr.vacuum_drying("gtocore:sphalerite_front_pro")
        .inputFluids("gtceu:sphalerite_front 4000")
        .itemOutputs("64x gtceu:zinc_dust", "64x gtceu:zinc_dust", "64x enderio:powdered_iron", "32x enderio:powdered_iron", "64x gtceu:indium_dust", "64x gtceu:gallium_dust")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(2400)
        .blastFurnaceTemp(5500)

    gtr.vacuum_drying("gtocore:pentlandite_front_pro")
        .inputFluids("gtceu:pentlandite_front 4000")
        .itemOutputs("64x enderio:powdered_iron", "64x enderio:powdered_iron", "64x gtceu:nickel_dust", "64x gtceu:nickel_dust", "64x gtceu:bismuth_dust", "48x gtceu:ruthenium_dust")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.LuV])
        .duration(2400)
        .blastFurnaceTemp(5500)

    gtr.vacuum_drying("gtocore:enriched_naquadah_front_pro")
    
        .inputFluids("gtceu:enriched_naquadah_front 4000")
        .itemOutputs("64x gtceu:enriched_naquadah_dust", "64x gtceu:enriched_naquadah_dust", "64x gtceu:naquadah_dust", "32x gtceu:naquadah_dust", "64x gtceu:naquadria_dust", "32x gtceu:trinium_dust")
        .outputFluids("gtceu:red_mud 200", "minecraft:water 2000")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(2400)
        .blastFurnaceTemp(9500)
})