ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.laser_engraver("gtocore:fullerene_dust")
        .itemInputs("gtceu:unfolded_fullerene_dust")
        .notConsumable("gtceu:ruby_lens")
        .inputFluids("gtceu:nitrogen 10000")
        .itemOutputs("gtceu:fullerene_dust")
        .outputFluids("gtceu:ammonia 10000")
        .EUt(2000000)
        .duration(400)
        .addDataBool("special", true)

    gtr.laser_engraver("gtocore:lanthanum_embedded_fullerene_dust")
        .itemInputs("2x gtceu:lanthanum_fullerene_mix_dust")
        .notConsumable("gtceu:sapphire_lens")
        .inputFluids("gtceu:nitrogen 10000")
        .itemOutputs("2x gtceu:lanthanum_embedded_fullerene_dust")
        .outputFluids("gtceu:ammonia 10000")
        .EUt(1966080)
        .duration(320)
        .addDataBool("special", true)

    gtr.laser_engraver("gtocore:singularity")
        .itemInputs("16x gtceu:magmatter_block")
        .itemInputs(Item.of("avaritia:singularity", `{Id:"avaritia:spacetime"}`).weakNBT())
        .itemOutputs("avaritia:singularity")
        .EUt(GTValues.VA[GTValues.MAX] * 262144)
        .duration(1600)

    gtr.laser_engraver("gtocore:exotic_wafer")
        .notConsumable("gtceu:magenta_glass_lens")
        .itemInputs("gtceu:highly_advanced_soc_wafer")
        .itemOutputs("gtocore:exotic_wafer")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(600)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:diffractor_grating_mirror")
        .itemInputs("gtocore:photocoated_hassium_wafer")
        .notConsumable("gtocore:grating_lithography_mask")
        .itemOutputs("gtocore:diffractor_grating_mirror")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(600)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:ilc_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/red")
        .itemOutputs("64x gtceu:ilc_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:ram_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/green")
        .itemOutputs("64x gtceu:ram_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:lpic_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/orange")
        .itemOutputs("64x gtceu:lpic_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:simple_soc_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/cyan")
        .itemOutputs("64x gtceu:simple_soc_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:ulpic_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/blue")
        .itemOutputs("64x gtceu:ulpic_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:cpu_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/light_blue")
        .itemOutputs("64x gtceu:cpu_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:soc_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/yellow")
        .itemOutputs("32x gtceu:soc_wafer")
        .EUt(122880)
        .duration(50)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:nor_memory_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/pink")
        .itemOutputs("32x gtceu:nor_memory_wafer")
        .EUt(122880)
        .duration(50)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:mpic_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/brown")
        .itemOutputs("32x gtceu:mpic_wafer")
        .EUt(122880)
        .duration(50)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:nand_memory_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/gray")
        .itemOutputs("32x gtceu:nand_memory_wafer")
        .EUt(122880)
        .duration(50)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:advanced_soc_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/purple")
        .itemOutputs("8x gtceu:advanced_soc_wafer")
        .EUt(122880)
        .duration(125)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtocore:highly_advanced_soc_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/black")
        .itemOutputs("4x gtceu:highly_advanced_soc_wafer")
        .EUt(122880)
        .duration(225)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.precision_laser_engraver("gtocore:prepared_cosmic_soc_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("gtocore:lithography_mask")
        .notConsumable("#forge:gt_lenses/yellow")
        .notConsumable("#forge:gt_lenses/lime")
        .notConsumable("#forge:gt_lenses/light_blue")
        .notConsumable("#forge:gt_lenses/cyan")
        .notConsumable("#forge:gt_lenses/purple")
        .notConsumable("#forge:gt_lenses/black")
        .notConsumable("#forge:gt_lenses/blue")
        .inputFluids("gtceu:gamma_rays_photoresist 1000")
        .itemOutputs("gtocore:prepared_cosmic_soc_wafer")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(4800)
        .CWUt(1024)

    gtr.precision_laser_engraver("gtocore:high_precision_crystal_soc")
        .itemInputs("gtceu:crystal_soc")
        .notConsumable("gtocore:lithography_mask")
        .notConsumable("#forge:gt_lenses/yellow")
        .notConsumable("#forge:gt_lenses/lime")
        .notConsumable("#forge:gt_lenses/light_blue")
        .notConsumable("#forge:gt_lenses/cyan")
        .notConsumable("#forge:gt_lenses/purple")
        .notConsumable("#forge:gt_lenses/black")
        .notConsumable("#forge:gt_lenses/blue")
        .inputFluids("gtceu:euv_photoresist 1000")
        .itemOutputs("gtocore:high_precision_crystal_soc")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2400)
        .CWUt(256)

    gtr.precision_laser_engraver("gtocore:nm_wafer")
        .itemInputs("gtocore:rutherfordium_neutronium_wafer")
        .notConsumable("gtocore:lithography_mask")
        .notConsumable("#forge:gt_lenses/blue")
        .notConsumable("#forge:gt_lenses/brown")
        .notConsumable("#forge:gt_lenses/orange")
        .notConsumable("#forge:gt_lenses/red")
        .notConsumable("gtceu:lime_glass_lens")
        .notConsumable("#forge:gt_lenses/pink")
        .notConsumable("#forge:gt_lenses/gray")
        .inputFluids("gtceu:photoresist 1000")
        .itemOutputs("gtocore:nm_wafer")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(900)
        .CWUt(128)

    gtr.precision_laser_engraver("gtocore:pm_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("gtocore:lithography_mask")
        .notConsumable("#forge:gt_lenses/blue")
        .notConsumable("#forge:gt_lenses/brown")
        .notConsumable("#forge:gt_lenses/orange")
        .notConsumable("#forge:gt_lenses/red")
        .notConsumable("gtceu:lime_glass_lens")
        .notConsumable("#forge:gt_lenses/pink")
        .notConsumable("#forge:gt_lenses/gray")
        .inputFluids("gtceu:euv_photoresist 1000")
        .itemOutputs("gtocore:pm_wafer")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(1800)
        .CWUt(256)

    gtr.precision_laser_engraver("gtocore:fm_wafer")
        .itemInputs("gtocore:pm_wafer")
        .notConsumable("gtocore:grating_lithography_mask")
        .notConsumable("#forge:gt_lenses/blue")
        .notConsumable("#forge:gt_lenses/brown")
        .notConsumable("#forge:gt_lenses/orange")
        .notConsumable("#forge:gt_lenses/red")
        .notConsumable("gtceu:lime_glass_lens")
        .notConsumable("#forge:gt_lenses/pink")
        .notConsumable("#forge:gt_lenses/gray")
        .inputFluids("gtceu:gamma_rays_photoresist 1000")
        .itemOutputs("gtocore:fm_wafer")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2800)
        .CWUt(512)

    gtr.precision_laser_engraver("gtocore:raw_photon_carrying_wafer")
        .itemInputs("gtocore:rutherfordium_neutronium_wafer")
        .notConsumable("gtocore:lithography_mask")
        .notConsumable("#forge:gt_lenses/light_gray")
        .notConsumable("#forge:gt_lenses/purple")
        .notConsumable("#forge:gt_lenses/yellow")
        .notConsumable("#forge:gt_lenses/magenta")
        .notConsumable("#forge:gt_lenses/orange")
        .notConsumable("#forge:gt_lenses/light_blue")
        .notConsumable("#forge:gt_lenses/pink")
        .itemOutputs("gtocore:raw_photon_carrying_wafer")
        .inputFluids("gtceu:photoresist 1000")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(600)
        .CWUt(128)

    gtr.dimensional_focus_engraving_array("gtocore:raw_photon_carrying_wafer")
        .itemInputs("gtocore:rutherfordium_neutronium_wafer")
        .notConsumable("#forge:gt_lenses/yellow")
        .inputFluids("gtceu:photoresist 100")
        .itemOutputs("gtocore:raw_photon_carrying_wafer")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(600)
        .CWUt(1)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtocore:raw_photon_carrying_wafer"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(2400))

    gtr.dimensional_focus_engraving_array("gtocore:prepared_cosmic_soc_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/light_blue")
        .inputFluids("gtceu:gamma_rays_photoresist 100")
        .itemOutputs("gtocore:prepared_cosmic_soc_wafer")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(4800)
        .CWUt(8)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtocore:prepared_cosmic_soc_wafer"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(2400))

    gtr.dimensional_focus_engraving_array("gtocore:high_precision_crystal_soc")
        .itemInputs("gtceu:crystal_soc")
        .notConsumable("#forge:gt_lenses/lime")
        .inputFluids("gtceu:euv_photoresist 100")
        .itemOutputs("gtocore:high_precision_crystal_soc")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2400)
        .CWUt(2)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtocore:high_precision_crystal_soc"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2400))

    gtr.dimensional_focus_engraving_array("gtocore:nm_wafer")
        .itemInputs("gtocore:rutherfordium_neutronium_wafer")
        .notConsumable("#forge:gt_lenses/blue")
        .inputFluids("gtceu:photoresist 100")
        .itemOutputs("gtocore:nm_wafer")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(900)
        .CWUt(1)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtocore:nm_wafer"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UV])
        .duration(2400))

    gtr.dimensional_focus_engraving_array("gtocore:pm_wafer")
        .itemInputs("gtocore:taranium_wafer")
        .notConsumable("#forge:gt_lenses/magenta")
        .inputFluids("gtceu:euv_photoresist 100")
        .itemOutputs("gtocore:pm_wafer")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(1800)
        .CWUt(2)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtocore:pm_wafer"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(2400))

    gtr.dimensional_focus_engraving_array("gtocore:fm_wafer")
        .itemInputs("gtocore:pm_wafer")
        .notConsumable("#forge:gt_lenses/orange")
        .inputFluids("gtceu:gamma_rays_photoresist 100")
        .itemOutputs("gtocore:fm_wafer")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2700)
        .CWUt(4)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtocore:fm_wafer"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2400))
})